-- GENERATED FILE — do not edit by hand.
-- Source: scripts/generate-catalog-v2-aliases.mjs (src/domains/estimating/pricing/intentMapV2.ts)
INSERT INTO public.catalog_intent_aliases
  (library_version, alias_norm, match_kind, assembly_key, quantity_factor, role, priority, review_reason, note) VALUES
  (2, 'mobilization', 'contains', 'gc.mobilization.crew', 1, 'mobilization', 100, NULL, NULL),
  (2, 'site protection', 'contains', 'gc.protection.floorpath', 1, 'protection', 100, NULL, NULL),
  (2, 'protect floors', 'contains', 'gc.protection.floorpath', 1, 'floor protection', 100, NULL, NULL),
  (2, 'dust containment', 'contains', 'gc.protection.dustwall', 1, 'dust barrier', 100, NULL, NULL),
  (2, 'dust barrier', 'contains', 'gc.protection.dustwall', 1, 'dust barrier', 100, NULL, NULL),
  (2, 'final clean', 'contains', 'gc.cleanup.final', 1, 'final cleaning', 100, NULL, NULL),
  (2, 'final cleaning', 'contains', 'gc.cleanup.final', 1, 'final cleaning', 100, NULL, NULL),
  (2, 'daily cleanup', 'contains', 'gc.cleanup.daily', 1, 'daily cleanup', 100, NULL, NULL),
  (2, 'dumpster', 'contains', 'gc.dumpster.20yd', 1, 'dumpster', 80, NULL, NULL),
  (2, 'roll off', 'contains', 'gc.dumpster.20yd', 1, 'dumpster', 100, NULL, NULL),
  (2, 'portable toilet', 'contains', 'gc.portable.toilet', 1, 'sanitation', 100, NULL, NULL),
  (2, 'equipment rental', 'contains', 'gc.equipment.rental', 1, 'equipment rental', 100, NULL, NULL),
  (2, 'temporary power', 'contains', 'gc.temp.power', 1, 'temporary power', 100, NULL, NULL),
  (2, 'service call minimum', 'contains', 'gc.servicecall.minimum', 1, 'small-job minimum', 100, NULL, NULL),
  (2, 'trip charge', 'contains', 'gc.servicecall.minimum', 1, 'small-job minimum', 100, NULL, NULL),
  (2, 'demolition permit', 'contains', 'permits.demolition.fee', 1, 'permit fee', 100, NULL, NULL),
  (2, 'roofing permit', 'contains', 'permits.roofing.fee', 1, 'permit fee', 100, NULL, NULL),
  (2, 'plan review', 'contains', 'permits.plan.review', 1, 'plan review fee', 100, NULL, NULL),
  (2, 'demo ceiling drywall', 'contains', 'demo.ceiling.drywall', 1, 'ceiling demo', 100, NULL, NULL),
  (2, 'remove plaster', 'contains', 'demo.plaster.walls', 1, 'plaster demo', 100, NULL, NULL),
  (2, 'remove sheet vinyl', 'contains', 'demo.flooring.vinyl', 1, 'vinyl demo', 100, NULL, NULL),
  (2, 'remove laminate flooring', 'contains', 'demo.flooring.laminate', 1, 'laminate demo', 100, NULL, NULL),
  (2, 'remove wall tile', 'contains', 'demo.tile.wall', 1, 'wall tile demo', 100, NULL, NULL),
  (2, 'demo shower tile', 'contains', 'demo.tile.wall', 1, 'shower tile demo', 100, NULL, NULL),
  (2, 'remove countertops', 'contains', 'demo.countertop.remove', 1, 'countertop demo', 92, NULL, NULL),
  (2, 'remove vanity', 'contains', 'demo.vanity.remove', 1, 'vanity demo', 100, NULL, NULL),
  (2, 'remove toilet', 'contains', 'demo.toilet.remove', 1, 'toilet demo', 100, NULL, NULL),
  (2, 'remove window', 'contains', 'demo.window.remove', 1, 'window demo', 88, NULL, NULL),
  (2, 'remove drop ceiling', 'contains', 'demo.ceiling.acoustic', 1, 'acoustic ceiling demo', 100, NULL, NULL),
  (2, 'selective demolition', 'contains', 'demo.selective.interior', 1, 'selective demo', 100, NULL, NULL),
  (2, 'remove subfloor', 'contains', 'demo.subfloor.remove', 1, 'subfloor demo', 100, NULL, NULL),
  (2, 'tear off roof', 'contains', 'demo.roof.tearoff', 1, 'roof tear-off', 100, NULL, NULL),
  (2, 'roof tear off', 'contains', 'demo.roof.tearoff', 1, 'roof tear-off', 100, NULL, NULL),
  (2, 'remove siding', 'contains', 'demo.siding.remove', 1, 'siding demo', 100, NULL, NULL),
  (2, 'remove existing deck', 'contains', 'demo.deck.remove', 1, 'deck demo', 100, NULL, NULL),
  (2, 'break out concrete', 'contains', 'demo.concrete.slab', 1, 'concrete demo', 100, NULL, NULL),
  (2, 'remove fence', 'contains', 'demo.fence.remove', 1, 'fence demo', 100, NULL, NULL),
  (2, 'frame interior partition', 'contains', 'framing.wall.partition.2x4', 1, 'partition framing', 95, NULL, NULL),
  (2, 'frame partition wall', 'contains', 'framing.wall.partition.2x4', 1, 'partition framing', 95, NULL, NULL),
  (2, 'frame 2x6 wall', 'contains', 'framing.wall.partition.2x6', 1, 'partition framing', 100, NULL, NULL),
  (2, 'knee wall', 'contains', 'framing.wall.knee', 1, 'knee wall framing', 100, NULL, NULL),
  (2, 'build soffit', 'contains', 'framing.soffit.build', 1, 'soffit framing', 100, NULL, NULL),
  (2, 'bulkhead', 'contains', 'framing.soffit.build', 1, 'bulkhead framing', 70, NULL, NULL),
  (2, 'furring strips', 'contains', 'framing.furring.wall', 1, 'furring', 100, NULL, NULL),
  (2, 'platform floor', 'contains', 'framing.floor.platform', 1, 'platform framing', 100, NULL, NULL),
  (2, 'sister joists', 'contains', 'framing.floor.sister', 1, 'joist reinforcement', 100, NULL, NULL),
  (2, 'replace subfloor', 'contains', 'framing.subfloor.replace', 1, 'subfloor replacement', 100, NULL, NULL),
  (2, 'flush beam', 'contains', 'framing.beam.flush', 1, 'structural beam', 100, NULL, NULL),
  (2, 'steel column', 'contains', 'framing.column.steel', 1, 'steel column', 100, NULL, NULL),
  (2, 'enlarge opening', 'contains', 'framing.opening.enlarge', 1, 'opening enlargement', 100, NULL, NULL),
  (2, 'frame stairs', 'contains', 'framing.stair.build', 1, 'stair framing', 100, NULL, NULL),
  (2, 'frame dormer', 'contains', 'framing.roof.dormer', 1, 'dormer framing', 100, NULL, NULL),
  (2, 'wall sheathing', 'contains', 'framing.sheathing.wall', 1, 'sheathing', 100, NULL, NULL),
  (2, 'hang drywall', 'contains', 'drywall.hang.walls', 1, 'board walls', 100, NULL, NULL),
  (2, 'hang and finish drywall', 'contains', 'drywall.hang.walls', 1, 'board', 95, NULL, NULL),
  (2, 'hang and finish drywall', 'contains', 'drywall.finish.level4', 1, 'tape and finish', 95, NULL, NULL),
  (2, 'drywall ceilings', 'contains', 'drywall.hang.ceiling', 1, 'ceiling board', 100, NULL, NULL),
  (2, 'cement board', 'contains', 'drywall.hang.cementboard', 1, 'backer board', 100, NULL, NULL),
  (2, 'backer board', 'contains', 'drywall.hang.cementboard', 1, 'backer board', 100, NULL, NULL),
  (2, 'level 5 finish', 'contains', 'drywall.finish.level5', 1, 'level 5 finish', 100, NULL, NULL),
  (2, 'tape and finish', 'contains', 'drywall.finish.level4', 1, 'tape and finish', 100, NULL, NULL),
  (2, 'skim coat', 'contains', 'drywall.skimcoat.walls', 1, 'skim coat', 100, NULL, NULL),
  (2, 'knockdown texture', 'contains', 'drywall.texture.knockdown', 1, 'texture', 100, NULL, NULL),
  (2, 'corner bead', 'contains', 'drywall.cornerbead.install', 1, 'corner bead', 100, NULL, NULL),
  (2, 'patch drywall hole', 'contains', 'drywall.patch.small', 1, 'drywall patch', 100, NULL, NULL),
  (2, 'small drywall patch', 'contains', 'drywall.patch.small', 1, 'drywall patch', 100, NULL, NULL),
  (2, 'drywall patch', 'contains', 'drywall.patch.medium', 1, 'drywall patch', 85, NULL, NULL),
  (2, 'ceiling repair', 'contains', 'drywall.ceiling.repair', 1, 'ceiling repair', 100, NULL, NULL),
  (2, 'plaster repair', 'contains', 'drywall.plaster.repair', 1, 'plaster repair', 100, NULL, NULL),
  (2, 'prime and paint ceilings', 'contains', 'painting.prime.ceiling', 1, 'primer', 95, NULL, NULL),
  (2, 'prime and paint ceilings', 'contains', 'painting.ceiling.twocoat', 1, 'ceiling finish', 95, NULL, NULL),
  (2, 'paint ceilings', 'contains', 'painting.ceiling.twocoat', 1, 'ceiling paint', 100, NULL, NULL),
  (2, 'paint ceiling', 'contains', 'painting.ceiling.twocoat', 1, 'ceiling paint', 100, NULL, NULL),
  (2, 'repaint walls', 'contains', 'painting.walls.onecoat', 1, 'wall refresh', 100, NULL, NULL),
  (2, 'accent wall', 'contains', 'painting.accent.wall', 1, 'accent wall', 100, NULL, NULL),
  (2, 'paint trim', 'contains', 'painting.trim.casing', 1, 'trim paint', 95, NULL, NULL),
  (2, 'paint casing', 'contains', 'painting.trim.casing', 1, 'trim paint', 95, NULL, NULL),
  (2, 'paint baseboard', 'contains', 'painting.trim.casing', 1, 'trim paint', 96, NULL, NULL),
  (2, 'paint doors', 'contains', 'painting.door.each', 1, 'door paint', 95, NULL, NULL),
  (2, 'paint door', 'contains', 'painting.door.each', 1, 'door paint', 94, NULL, NULL),
  (2, 'paint cabinets', 'contains', 'painting.cabinets.spray', 1, 'cabinet painting', 96, NULL, NULL),
  (2, 'paint kitchen cabinets', 'contains', 'painting.cabinets.spray', 1, 'cabinet painting', 97, NULL, NULL),
  (2, 'refinish cabinets', 'contains', 'painting.cabinets.spray', 1, 'cabinet refinishing', 95, NULL, NULL),
  (2, 'stain trim', 'contains', 'painting.stain.trim', 1, 'trim stain', 100, NULL, NULL),
  (2, 'paint prep', 'contains', 'painting.prep.patchsand', 1, 'paint prep', 100, NULL, NULL),
  (2, 'paint exterior siding', 'contains', 'painting.exterior.siding', 1, 'exterior paint', 95, NULL, NULL),
  (2, 'exterior painting', 'contains', 'painting.exterior.siding', 1, 'exterior paint', 100, NULL, NULL),
  (2, 'paint exterior trim', 'contains', 'painting.exterior.trim', 1, 'exterior trim paint', 95, NULL, NULL),
  (2, 'stain deck', 'contains', 'painting.deck.stain', 1, 'deck stain', 100, NULL, NULL),
  (2, 'power wash and prep', 'contains', 'painting.exterior.prep', 1, 'exterior prep', 100, NULL, NULL),
  (2, 'paint railing', 'contains', 'painting.stairs.railing', 1, 'railing finish', 100, NULL, NULL),
  (2, 'install lvp', 'contains', 'flooring.lvp.install', 1, 'LVP', 95, NULL, NULL),
  (2, 'install luxury vinyl plank', 'contains', 'flooring.lvp.install', 1, 'LVP', 95, NULL, NULL),
  (2, 'install vinyl plank', 'contains', 'flooring.lvp.install', 1, 'LVP', 100, NULL, NULL),
  (2, 'lvp', 'contains', 'flooring.lvp.install', 1, 'LVP', 60, NULL, NULL),
  (2, 'vinyl plank', 'contains', 'flooring.lvp.install', 1, 'LVP', 70, NULL, NULL),
  (2, 'install laminate flooring', 'contains', 'flooring.laminate.install', 1, 'laminate', 100, NULL, NULL),
  (2, 'install hardwood flooring', 'contains', 'flooring.hardwood.solid', 1, 'hardwood', 95, NULL, NULL),
  (2, 'install engineered hardwood', 'contains', 'flooring.hardwood.engineered', 1, 'engineered hardwood', 96, NULL, NULL),
  (2, 'install carpet', 'contains', 'flooring.carpet.install', 1, 'carpet and pad', 100, NULL, NULL),
  (2, 'install sheet vinyl', 'contains', 'flooring.vinyl.sheet', 1, 'sheet vinyl', 100, NULL, NULL),
  (2, 'install underlayment', 'contains', 'flooring.underlayment.install', 1, 'underlayment', 100, NULL, NULL),
  (2, 'self leveling', 'contains', 'flooring.prep.selflevel', 1, 'floor levelling', 100, NULL, NULL),
  (2, 'self leveling', 'contains', 'flooring.prep.selflevel', 1, 'floor levelling', 100, NULL, NULL),
  (2, 'grind slab', 'contains', 'flooring.prep.grind', 1, 'slab prep', 100, NULL, NULL),
  (2, 'refinish hardwood', 'contains', 'flooring.refinish.sand', 1, 'sand and refinish', 95, NULL, NULL),
  (2, 'sand and refinish floors', 'contains', 'flooring.refinish.sand', 1, 'sand and refinish', 100, NULL, NULL),
  (2, 'stair treads', 'contains', 'flooring.stair.treads', 1, 'treads and risers', 100, NULL, NULL),
  (2, 'shower wall tile', 'contains', 'tile.shower.wall', 1, 'shower wall tile', 96, NULL, NULL),
  (2, 'shower tile', 'contains', 'tile.shower.wall', 1, 'shower wall tile', 94, NULL, 'Priced from the shower''s own tiled area — room floor area is not valid evidence for shower tile.'),
  (2, 'shower floor tile', 'contains', 'tile.shower.floor', 1, 'shower floor tile', 97, NULL, NULL),
  (2, 'bathroom floor tile', 'contains', 'tile.bath.floor', 1, 'bath floor tile', 95, NULL, NULL),
  (2, 'install backsplash', 'contains', 'tile.backsplash.kitchen', 1, 'backsplash', 95, NULL, NULL),
  (2, 'backsplash tile', 'contains', 'tile.backsplash.kitchen', 1, 'backsplash', 95, NULL, NULL),
  (2, 'waterproof shower', 'contains', 'tile.waterproof.membrane', 1, 'waterproofing', 100, NULL, NULL),
  (2, 'waterproofing membrane', 'contains', 'tile.waterproof.membrane', 1, 'waterproofing', 100, NULL, NULL),
  (2, 'mud pan', 'contains', 'tile.shower.pan.mud', 1, 'shower pan', 100, NULL, NULL),
  (2, 'shower pan', 'contains', 'tile.shower.pan.mud', 1, 'shower pan', 88, NULL, NULL),
  (2, 'shower curb', 'contains', 'tile.shower.curb', 1, 'curb', 100, NULL, NULL),
  (2, 'grout and seal', 'contains', 'tile.grout.seal', 1, 'grout and seal', 100, NULL, NULL),
  (2, 'tile edge trim', 'contains', 'tile.schluter.trim', 1, 'edge profile', 100, NULL, NULL),
  (2, 'heated floor', 'contains', 'tile.floor.heat', 1, 'floor heat', 100, NULL, NULL),
  (2, 'tile bathroom', 'contains', NULL, 1, NULL, 70, 'ambiguous_multi_scope', 'Split the tile scope into shower walls, shower floor and bathroom floor — each is measured separately.'),
  (2, 'install shutoffs and supply lines', 'contains', 'plumbing.shutoff.angle', 1, 'angle stops', 97, NULL, 'Decomposed into stops and supply lines — confirm the fixture count; one valve is not the whole scope.'),
  (2, 'install shutoffs and supply lines', 'contains', 'plumbing.supply.line', 1, 'supply lines', 97, NULL, 'Decomposed into stops and supply lines — confirm the fixture count; one valve is not the whole scope.'),
  (2, 'shutoffs and supply lines', 'contains', 'plumbing.shutoff.angle', 1, 'angle stops', 96, NULL, NULL),
  (2, 'shutoffs and supply lines', 'contains', 'plumbing.supply.line', 1, 'supply lines', 96, NULL, NULL),
  (2, 'bathroom plumbing connections', 'contains', 'plumbing.bath.connections.allowance', 1, 'bathroom connection allowance', 100, NULL, NULL),
  (2, 'hook up fixtures', 'contains', 'plumbing.bath.connections.allowance', 1, 'fixture connection allowance', 100, NULL, NULL),
  (2, 'kitchen plumbing', 'contains', 'plumbing.kitchen.connections.allowance', 1, 'kitchen connection allowance', 100, NULL, NULL),
  (2, 'angle stop', 'contains', 'plumbing.shutoff.angle', 1, 'angle stop', 100, NULL, NULL),
  (2, 'set toilet', 'contains', 'plumbing.toilet.set', 1, 'toilet', 100, NULL, NULL),
  (2, 'install toilet', 'contains', 'plumbing.toilet.set', 1, 'toilet', 100, NULL, NULL),
  (2, 'install lavatory', 'contains', 'plumbing.lav.set', 1, 'lavatory', 100, NULL, NULL),
  (2, 'install bathroom sink', 'contains', 'plumbing.lav.set', 1, 'lavatory', 100, NULL, NULL),
  (2, 'install kitchen sink', 'contains', 'plumbing.kitchen.sink', 1, 'kitchen sink', 95, NULL, NULL),
  (2, 'replace faucet', 'contains', 'plumbing.faucet.replace', 1, 'faucet', 100, NULL, NULL),
  (2, 'install faucet', 'contains', 'plumbing.faucet.replace', 1, 'faucet', 100, NULL, NULL),
  (2, 'garbage disposal', 'contains', 'plumbing.disposal.install', 1, 'disposal', 100, NULL, NULL),
  (2, 'dishwasher connection', 'contains', 'plumbing.dishwasher.connect', 1, 'dishwasher hookup', 100, NULL, NULL),
  (2, 'set tub', 'contains', 'plumbing.tub.set', 1, 'bathtub', 100, NULL, NULL),
  (2, 'install bathtub', 'contains', 'plumbing.tub.set', 1, 'bathtub', 100, NULL, NULL),
  (2, 'shower valve', 'contains', 'plumbing.shower.valve', 1, 'shower valve', 90, NULL, NULL),
  (2, 'shower head', 'contains', 'plumbing.showerhead.install', 1, 'shower head', 100, NULL, NULL),
  (2, 'hose bib', 'contains', 'plumbing.hosebib.install', 1, 'hose bib', 100, NULL, NULL),
  (2, 'laundry hookup', 'contains', 'plumbing.laundry.box', 1, 'laundry box', 100, NULL, NULL),
  (2, 'water heater', 'contains', 'plumbing.waterheater.tank', 1, 'water heater', 85, NULL, NULL),
  (2, 'tankless water heater', 'contains', 'plumbing.waterheater.tankless', 1, 'tankless heater', 95, NULL, NULL),
  (2, 'drain waste and vent', 'contains', 'plumbing.dwv.rough', 1, 'DWV rough-in', 100, NULL, NULL),
  (2, 'dwv rough', 'contains', 'plumbing.dwv.rough', 1, 'DWV rough-in', 100, NULL, NULL),
  (2, 'water rough in', 'contains', 'plumbing.water.rough', 1, 'water rough-in', 100, NULL, NULL),
  (2, 'relocate plumbing', 'contains', 'plumbing.fixture.relocate', 1, 'fixture relocation', 100, NULL, NULL),
  (2, 'gas line', 'contains', 'plumbing.gas.line', 1, 'gas line', 100, NULL, NULL),
  (2, 'new circuits outlets lighting', 'contains', 'electrical.room.package.allowance', 1, 'room electrical allowance', 120, NULL, 'Bundled electrical scope priced as a disclosed room package allowance — confirm device and circuit counts for the detailed estimate.'),
  (2, 'circuits outlets and lighting', 'contains', 'electrical.room.package.allowance', 1, 'room electrical allowance', 118, NULL, NULL),
  (2, 'outlets and lighting', 'contains', 'electrical.room.package.allowance', 1, 'room electrical allowance', 90, NULL, NULL),
  (2, 'bathroom electrical', 'contains', 'electrical.bath.package.allowance', 1, 'bath electrical allowance', 100, NULL, NULL),
  (2, 'kitchen electrical', 'contains', 'electrical.kitchen.package.allowance', 1, 'kitchen electrical allowance', 100, NULL, NULL),
  (2, 'install receptacle', 'contains', 'electrical.receptacle.standard', 1, 'receptacle', 100, NULL, NULL),
  (2, 'install outlet', 'contains', 'electrical.receptacle.standard', 1, 'receptacle', 100, NULL, NULL),
  (2, 'gfci receptacle', 'contains', 'electrical.receptacle.gfci', 1, 'GFCI receptacle', 95, NULL, NULL),
  (2, 'install switch', 'contains', 'electrical.switch.single', 1, 'switch', 100, NULL, NULL),
  (2, 'dimmer', 'contains', 'electrical.switch.dimmer', 1, 'dimmer', 85, NULL, NULL),
  (2, 'smoke detector', 'contains', 'electrical.smoke.co', 1, 'smoke/CO detector', 100, NULL, NULL),
  (2, 'recessed lighting', 'contains', 'electrical.light.recessed', 1, 'recessed lights', 95, NULL, NULL),
  (2, 'can lights', 'contains', 'electrical.light.recessed', 1, 'recessed lights', 100, NULL, NULL),
  (2, 'install light fixture', 'contains', 'electrical.light.surface', 1, 'light fixture', 100, NULL, NULL),
  (2, 'vanity light', 'contains', 'electrical.light.vanity', 1, 'vanity light', 100, NULL, NULL),
  (2, 'ceiling fan', 'contains', 'electrical.fan.ceiling', 1, 'ceiling fan', 100, NULL, NULL),
  (2, 'under cabinet lighting', 'contains', 'electrical.light.undercabinet', 1, 'under-cabinet lighting', 97, NULL, NULL),
  (2, 'under cabinet lighting', 'contains', 'electrical.light.undercabinet', 1, 'under-cabinet lighting', 97, NULL, NULL),
  (2, 'exterior light', 'contains', 'electrical.light.exterior', 1, 'exterior fixture', 100, NULL, NULL),
  (2, 'new circuit', 'contains', 'electrical.circuit.new', 1, 'branch circuit', 88, NULL, NULL),
  (2, 'appliance circuit', 'contains', 'electrical.circuit.appliance', 1, 'appliance circuit', 100, NULL, NULL),
  (2, 'extend circuit', 'contains', 'electrical.circuit.extend', 1, 'circuit extension', 100, NULL, NULL),
  (2, 'subpanel', 'contains', 'electrical.panel.subpanel', 1, 'subpanel', 100, NULL, NULL),
  (2, 'panel upgrade', 'contains', 'electrical.panel.upgrade', 1, 'service upgrade', 100, NULL, NULL),
  (2, 'low voltage', 'contains', 'electrical.lowvoltage.run', 1, 'low-voltage drop', 100, NULL, NULL),
  (2, 'extend supply duct', 'contains', 'hvac.supply.extend', 1, 'supply run', 100, NULL, NULL),
  (2, 'add return air', 'contains', 'hvac.return.add', 1, 'return drop', 100, NULL, NULL),
  (2, 'relocate register', 'contains', 'hvac.register.relocate', 1, 'register relocation', 100, NULL, NULL),
  (2, 'duct modification', 'contains', 'hvac.duct.modify', 1, 'duct modification', 100, NULL, NULL),
  (2, 'bath fan', 'contains', 'hvac.bathfan.install', 1, 'bath exhaust fan', 90, NULL, NULL),
  (2, 'exhaust fan', 'contains', 'hvac.bathfan.install', 1, 'exhaust fan', 88, NULL, NULL),
  (2, 'range hood vent', 'contains', 'hvac.rangehood.vent', 1, 'range hood venting', 100, NULL, NULL),
  (2, 'dryer vent', 'contains', 'hvac.dryer.vent', 1, 'dryer vent', 100, NULL, NULL),
  (2, 'mini split', 'contains', 'hvac.minisplit.single', 1, 'mini-split system', 100, NULL, NULL),
  (2, 'mini split', 'contains', 'hvac.minisplit.single', 1, 'mini-split system', 100, NULL, NULL),
  (2, 'thermostat', 'contains', 'hvac.thermostat.install', 1, 'thermostat', 80, NULL, NULL),
  (2, 'rigid foam', 'contains', 'insulation.rigid.foam', 1, 'rigid foam', 100, NULL, NULL),
  (2, 'spray foam', 'contains', 'insulation.spray.allowance', 1, 'spray foam allowance', 100, NULL, NULL),
  (2, 'rim joist', 'contains', 'insulation.rimjoist.seal', 1, 'rim joist insulation', 100, NULL, NULL),
  (2, 'air sealing', 'contains', 'insulation.airseal.package', 1, 'air sealing', 100, NULL, NULL),
  (2, 'sound insulation', 'contains', 'insulation.sound.batt', 1, 'sound batt', 100, NULL, NULL),
  (2, 'vapor barrier', 'contains', 'insulation.vapor.barrier', 1, 'vapor retarder', 100, NULL, NULL),
  (2, 'attic insulation', 'contains', 'insulation.attic.blown', 1, 'blown insulation', 100, NULL, NULL),
  (2, 'install prehung door', 'contains', 'doors.interior.prehung.install', 1, 'prehung door', 95, NULL, NULL),
  (2, 'install interior door', 'contains', 'doors.interior.prehung.install', 1, 'interior door', 94, NULL, NULL),
  (2, 'hang slab door', 'contains', 'doors.interior.slab', 1, 'slab door', 100, NULL, NULL),
  (2, 'bifold door', 'contains', 'doors.bifold.install', 1, 'bifold door', 100, NULL, NULL),
  (2, 'pocket door', 'contains', 'doors.pocket.install', 1, 'pocket door', 100, NULL, NULL),
  (2, 'barn door', 'contains', 'doors.barn.install', 1, 'barn door', 100, NULL, NULL),
  (2, 'install lockset', 'contains', 'doors.hardware.install', 1, 'door hardware', 100, NULL, NULL),
  (2, 'door hardware', 'contains', 'doors.hardware.install', 1, 'door hardware', 85, NULL, NULL),
  (2, 'adjust door', 'contains', 'doors.adjust.repair', 1, 'door adjustment', 100, NULL, NULL),
  (2, 'install entry door', 'contains', 'doors.entry.install', 1, 'entry door', 95, NULL, NULL),
  (2, 'exterior door', 'contains', 'doors.entry.install', 1, 'entry door', 86, NULL, NULL),
  (2, 'patio door', 'contains', 'doors.patio.slider', 1, 'patio door', 100, NULL, NULL),
  (2, 'storm door', 'contains', 'doors.storm.install', 1, 'storm door', 100, NULL, NULL),
  (2, 'replace window', 'contains', 'windows.replace.insert', 1, 'window replacement', 92, NULL, NULL),
  (2, 'install window', 'contains', 'windows.newconstruction.install', 1, 'window install', 90, NULL, NULL),
  (2, 'egress window', 'contains', 'windows.egress.install', 1, 'egress window', 96, NULL, NULL),
  (2, 'window sill', 'contains', 'windows.sill.interior', 1, 'sill and apron', 100, NULL, NULL),
  (2, 'install baseboard trim', 'contains', 'trim.base.install.paintgrade', 1, 'baseboard', 95, NULL, NULL),
  (2, 'install baseboard', 'contains', 'trim.base.install.paintgrade', 1, 'baseboard', 94, NULL, NULL),
  (2, 'install base trim', 'contains', 'trim.base.install.paintgrade', 1, 'baseboard', 93, NULL, NULL),
  (2, 'install shoe molding', 'contains', 'trim.shoe.quarter', 1, 'shoe molding', 100, NULL, NULL),
  (2, 'quarter round', 'contains', 'trim.shoe.quarter', 1, 'quarter round', 100, NULL, NULL),
  (2, 'case doors', 'contains', 'trim.casing.door', 1, 'door casing', 100, NULL, NULL),
  (2, 'install casing', 'contains', 'trim.casing.door', 1, 'casing', 90, NULL, NULL),
  (2, 'install crown molding', 'contains', 'trim.crown.install', 1, 'crown molding', 95, NULL, NULL),
  (2, 'wainscot', 'contains', 'trim.wainscot.panel', 1, 'wainscot', 100, NULL, NULL),
  (2, 'board and batten', 'contains', 'trim.wainscot.panel', 1, 'panelling', 100, NULL, NULL),
  (2, 'closet shelving', 'contains', 'trim.shelving.closet', 1, 'closet shelf and rod', 100, NULL, NULL),
  (2, 'closet system', 'contains', 'trim.closet.system', 1, 'closet organizer', 100, NULL, NULL),
  (2, 'install handrail', 'contains', 'trim.handrail.install', 1, 'handrail', 100, NULL, NULL),
  (2, 'trim repair', 'contains', 'trim.repair.patch', 1, 'trim repair', 100, NULL, NULL),
  (2, 'install kitchen cabinets', 'contains', 'cabinets.base.install', 1, 'base cabinets', 97, NULL, NULL),
  (2, 'install kitchen cabinets', 'contains', 'cabinets.wall.install', 1, 'wall cabinets', 97, NULL, NULL),
  (2, 'install base cabinets', 'contains', 'cabinets.base.install', 1, 'base cabinets', 95, NULL, NULL),
  (2, 'install wall cabinets', 'contains', 'cabinets.wall.install', 1, 'wall cabinets', 95, NULL, NULL),
  (2, 'install cabinets', 'contains', 'cabinets.base.install', 1, 'base cabinets', 92, NULL, NULL),
  (2, 'install cabinets', 'contains', 'cabinets.wall.install', 1, 'wall cabinets', 92, NULL, NULL),
  (2, 'pantry cabinet', 'contains', 'cabinets.tall.install', 1, 'tall cabinet', 100, NULL, NULL),
  (2, 'install vanity', 'contains', 'cabinets.vanity.install', 1, 'vanity', 95, NULL, NULL),
  (2, 'cabinet hardware', 'contains', 'cabinets.hardware.install', 1, 'cabinet hardware', 100, NULL, NULL),
  (2, 'cabinet crown', 'contains', 'cabinets.crown.install', 1, 'cabinet crown', 100, NULL, NULL),
  (2, 'quartz countertop', 'contains', 'countertops.quartz.install', 1, 'quartz top', 95, NULL, NULL),
  (2, 'granite countertop', 'contains', 'countertops.granite.install', 1, 'granite top', 95, NULL, NULL),
  (2, 'laminate countertop', 'contains', 'countertops.laminate.install', 1, 'laminate top', 95, NULL, NULL),
  (2, 'butcher block', 'contains', 'countertops.butcherblock.install', 1, 'butcher block top', 100, NULL, NULL),
  (2, 'solid surface countertop', 'contains', 'countertops.solidsurface.install', 1, 'solid-surface top', 100, NULL, NULL),
  (2, 'install countertops', 'contains', NULL, 1, NULL, 80, 'ambiguous_material_selection', 'Pick the countertop material (quartz, granite, laminate, solid surface or butcher block).'),
  (2, 'install shingles', 'contains', 'roofing.asphalt.install', 1, 'asphalt shingles', 95, NULL, NULL),
  (2, 'asphalt shingle roof', 'contains', 'roofing.asphalt.install', 1, 'asphalt shingles', 100, NULL, NULL),
  (2, 'roof underlayment', 'contains', 'roofing.underlayment.install', 1, 'underlayment', 100, NULL, NULL),
  (2, 'ice and water', 'contains', 'roofing.iceandwater.install', 1, 'ice barrier', 100, NULL, NULL),
  (2, 'ridge vent', 'contains', 'roofing.ridge.vent', 1, 'ridge vent', 100, NULL, NULL),
  (2, 'step flashing', 'contains', 'roofing.flashing.step', 1, 'flashing', 100, NULL, NULL),
  (2, 'pipe boot', 'contains', 'roofing.pipe.boot', 1, 'penetration flashing', 100, NULL, NULL),
  (2, 'sheathing repair', 'contains', 'roofing.sheathing.repair', 1, 'decking repair allowance', 100, NULL, NULL),
  (2, 'install vinyl siding', 'contains', 'siding.vinyl.install', 1, 'vinyl siding', 95, NULL, NULL),
  (2, 'fiber cement siding', 'contains', 'siding.fibercement.install', 1, 'fiber-cement siding', 95, NULL, NULL),
  (2, 'house wrap', 'contains', 'siding.wrap.install', 1, 'weather barrier', 100, NULL, NULL),
  (2, 'soffit and fascia', 'contains', 'siding.soffit.fascia', 1, 'soffit and fascia', 100, NULL, NULL),
  (2, 'siding repair', 'contains', 'siding.repair.patch', 1, 'siding repair', 100, NULL, NULL),
  (2, 'install gutters', 'contains', 'gutters.k5.install', 1, 'gutter', 95, NULL, NULL),
  (2, 'install gutters', 'contains', 'gutters.downspout.install', 0.25, 'downspouts', 95, NULL, NULL),
  (2, 'gutter guards', 'contains', 'gutters.guard.install', 1, 'gutter guards', 100, NULL, NULL),
  (2, 'downspout extension', 'contains', 'gutters.extension.drain', 1, 'downspout extension', 100, NULL, NULL),
  (2, 'pour concrete slab', 'contains', 'concrete.slab.pour', 1, 'slab', 95, NULL, NULL),
  (2, 'concrete walkway', 'contains', 'concrete.walkway.pour', 1, 'walkway', 100, NULL, NULL),
  (2, 'equipment pad', 'contains', 'concrete.pad.equipment', 1, 'equipment pad', 100, NULL, NULL),
  (2, 'pour footing', 'contains', 'concrete.footing.pour', 1, 'footing', 100, NULL, NULL),
  (2, 'concrete steps', 'contains', 'concrete.steps.pour', 1, 'steps', 100, NULL, NULL),
  (2, 'concrete repair', 'contains', 'concrete.patch.repair', 1, 'concrete repair', 100, NULL, NULL),
  (2, 'saw cut concrete', 'contains', 'concrete.saw.cut', 1, 'saw cutting', 100, NULL, NULL),
  (2, 'block wall', 'contains', 'masonry.block.wall', 1, 'CMU wall', 100, NULL, NULL),
  (2, 'frost wall', 'contains', 'masonry.frostwall.pour', 1, 'frost wall', 100, NULL, NULL),
  (2, 'tuckpoint', 'contains', 'masonry.tuckpoint.repair', 1, 'repointing', 100, NULL, NULL),
  (2, 'brick repair', 'contains', 'masonry.brick.repair', 1, 'brick repair', 100, NULL, NULL),
  (2, 'stone veneer', 'contains', 'masonry.veneer.stone', 1, 'stone veneer', 100, NULL, NULL),
  (2, 'chimney repair', 'contains', 'masonry.chimney.repair', 1, 'chimney repair', 100, NULL, NULL),
  (2, 'deck footing', 'contains', 'decks.footing.install', 1, 'footings', 100, NULL, NULL),
  (2, 'frame deck', 'contains', 'decks.framing.install', 1, 'deck framing', 95, NULL, NULL),
  (2, 'composite decking', 'contains', 'decks.decking.composite', 1, 'composite decking', 95, NULL, NULL),
  (2, 'install decking', 'contains', 'decks.decking.wood', 1, 'decking', 90, NULL, NULL),
  (2, 'deck stairs', 'contains', 'decks.stairs.build', 1, 'deck stairs', 100, NULL, NULL),
  (2, 'deck railing', 'contains', 'decks.railing.install', 1, 'deck railing', 95, NULL, NULL),
  (2, 'deck skirting', 'contains', 'decks.skirting.install', 1, 'skirting', 100, NULL, NULL),
  (2, 'deck repair', 'contains', 'decks.repair.boards', 1, 'deck repair', 100, NULL, NULL),
  (2, 'recaulk', 'contains', 'handyman.caulk.refresh', 1, 'caulk joint', 100, NULL, NULL),
  (2, 'replace caulk', 'contains', 'handyman.caulk.refresh', 1, 'caulk joint', 100, NULL, NULL),
  (2, 'install shelf', 'contains', 'handyman.shelf.install', 1, 'wall shelf', 100, NULL, NULL),
  (2, 'mount tv', 'contains', 'handyman.tv.mount', 1, 'TV mount', 100, NULL, NULL),
  (2, 'grab bar', 'contains', 'handyman.grabbar.install', 1, 'grab bar', 100, NULL, NULL),
  (2, 'toilet repair', 'contains', 'handyman.toilet.repair', 1, 'toilet repair', 100, NULL, NULL),
  (2, 'medicine cabinet', 'contains', 'handyman.mirror.install', 1, 'mirror/cabinet', 100, NULL, NULL),
  (2, 'towel bar', 'contains', 'handyman.towelbar.accessory', 1, 'bath accessory', 100, NULL, NULL),
  (2, 'screen repair', 'contains', 'handyman.screen.repair', 1, 'screen repair', 100, NULL, NULL),
  (2, 'punch list', 'contains', 'handyman.punch.hour', 1, 'punch-list labor', 100, NULL, NULL),
  (2, 'weatherstripping', 'contains', 'handyman.weatherstrip.door', 1, 'weatherstripping', 100, NULL, NULL),
  (2, 'rough grading', 'contains', 'site.grading.rough', 1, 'grading', 95, NULL, NULL),
  (2, 'grade around foundation', 'contains', 'site.grading.rough', 1, 'grading', 100, NULL, NULL),
  (2, 'excavate trench', 'contains', 'site.excavation.trench', 1, 'trenching', 100, NULL, NULL),
  (2, 'french drain', 'contains', 'site.drainage.french', 1, 'french drain', 100, NULL, NULL),
  (2, 'topsoil and seed', 'contains', 'site.topsoil.seed', 1, 'topsoil and seed', 100, NULL, NULL),
  (2, 'install sod', 'contains', 'site.sod.install', 1, 'sod', 100, NULL, NULL),
  (2, 'mulch beds', 'contains', 'site.mulch.beds', 1, 'mulch', 100, NULL, NULL),
  (2, 'retaining wall', 'contains', 'site.retaining.small', 1, 'retaining wall', 100, NULL, NULL),
  (2, 'privacy fence', 'contains', 'site.fence.privacy', 1, 'fence', 95, NULL, NULL),
  (2, 'install fence', 'contains', 'site.fence.privacy', 1, 'fence', 90, NULL, NULL)
ON CONFLICT (library_version, alias_norm, COALESCE(assembly_key, '')) DO NOTHING;
