/**
 * Business profile catalog — stable, language-neutral keys.
 * Labels are localized in i18n namespace "crm".
 */
import { PROJECT_CATEGORY_KEYS, type ProjectCategoryKey } from "./projectTypes";

export const PRIMARY_BUSINESS_TYPES = [
  "GENERAL_REMODELING",
  "HANDYMAN",
  "GENERAL_CONTRACTOR",
  "KITCHEN_BATH",
  "PAINTING",
  "ROOFING",
  "EXTERIOR_CONTRACTOR",
  "DECKS_OUTDOOR_LIVING",
  "ELECTRICAL",
  "PLUMBING",
  "HVAC",
  "FLOORING",
  "WINDOWS_DOORS",
  "MASONRY",
  "RESTORATION",
  "ACCESSIBILITY_AGING_IN_PLACE",
  "NEW_CONSTRUCTION",
  "DESIGN_BUILD",
  "PROPERTY_MAINTENANCE",
  "OTHER",
] as const;
export type PrimaryBusinessType = (typeof PRIMARY_BUSINESS_TYPES)[number];

export const PROJECT_SCALES = [
  "QUICK_REPAIR",
  "HALF_DAY",
  "FULL_DAY",
  "MULTI_DAY_SMALL_PROJECT",
  "REMODEL",
  "MAJOR_RENOVATION",
  "NEW_CONSTRUCTION",
] as const;
export type ProjectScaleKey = (typeof PROJECT_SCALES)[number];

/** Preferred-scale (org-level) additionally supports ALL_SIZES. */
export const PREFERRED_PROJECT_SCALES = [...PROJECT_SCALES, "ALL_SIZES"] as const;
export type PreferredProjectScaleKey = (typeof PREFERRED_PROJECT_SCALES)[number];

export function isPrimaryBusinessType(v: unknown): v is PrimaryBusinessType {
  return typeof v === "string" && (PRIMARY_BUSINESS_TYPES as readonly string[]).includes(v);
}
export function isProjectScaleKey(v: unknown): v is ProjectScaleKey {
  return typeof v === "string" && (PROJECT_SCALES as readonly string[]).includes(v);
}
export function isPreferredProjectScaleKey(v: unknown): v is PreferredProjectScaleKey {
  return typeof v === "string" && (PREFERRED_PROJECT_SCALES as readonly string[]).includes(v);
}

/**
 * Per-primary-business preferred category order.
 * Every entry lists ALL categories (unlisted categories are appended in
 * default order so the picker never hides an option).
 */
export const BUSINESS_TYPE_CATEGORY_ORDER: Record<PrimaryBusinessType, readonly ProjectCategoryKey[]> = {
  GENERAL_REMODELING: [
    "INTERIOR_REMODELING", "ADDITIONS_CONSTRUCTION", "OUTDOOR_LIVING", "EXTERIOR",
    "PAINTING", "ROOFING", "RESTORATION", "ACCESSIBILITY",
    "PLUMBING", "ELECTRICAL", "HVAC", "GENERAL",
  ],
  HANDYMAN: [
    "GENERAL", "INTERIOR_REMODELING", "PAINTING", "EXTERIOR",
    "PLUMBING", "ELECTRICAL", "OUTDOOR_LIVING", "ACCESSIBILITY",
    "ROOFING", "HVAC", "RESTORATION", "ADDITIONS_CONSTRUCTION",
  ],
  GENERAL_CONTRACTOR: [
    "ADDITIONS_CONSTRUCTION", "INTERIOR_REMODELING", "EXTERIOR", "ROOFING",
    "OUTDOOR_LIVING", "RESTORATION", "PAINTING", "ACCESSIBILITY",
    "PLUMBING", "ELECTRICAL", "HVAC", "GENERAL",
  ],
  KITCHEN_BATH: [
    "INTERIOR_REMODELING", "PLUMBING", "ELECTRICAL", "PAINTING",
    "ACCESSIBILITY", "GENERAL", "ADDITIONS_CONSTRUCTION", "OUTDOOR_LIVING",
    "EXTERIOR", "RESTORATION", "HVAC", "ROOFING",
  ],
  PAINTING: [
    "PAINTING", "INTERIOR_REMODELING", "EXTERIOR", "GENERAL",
    "RESTORATION", "OUTDOOR_LIVING", "ROOFING", "ADDITIONS_CONSTRUCTION",
    "ACCESSIBILITY", "PLUMBING", "ELECTRICAL", "HVAC",
  ],
  ROOFING: [
    "ROOFING", "EXTERIOR", "GENERAL", "RESTORATION",
    "ADDITIONS_CONSTRUCTION", "OUTDOOR_LIVING", "INTERIOR_REMODELING", "PAINTING",
    "ACCESSIBILITY", "PLUMBING", "ELECTRICAL", "HVAC",
  ],
  EXTERIOR_CONTRACTOR: [
    "EXTERIOR", "ROOFING", "OUTDOOR_LIVING", "PAINTING",
    "GENERAL", "RESTORATION", "ADDITIONS_CONSTRUCTION", "INTERIOR_REMODELING",
    "ACCESSIBILITY", "PLUMBING", "ELECTRICAL", "HVAC",
  ],
  DECKS_OUTDOOR_LIVING: [
    "OUTDOOR_LIVING", "EXTERIOR", "GENERAL", "ADDITIONS_CONSTRUCTION",
    "PAINTING", "ROOFING", "INTERIOR_REMODELING", "RESTORATION",
    "ACCESSIBILITY", "ELECTRICAL", "PLUMBING", "HVAC",
  ],
  ELECTRICAL: [
    "ELECTRICAL", "GENERAL", "INTERIOR_REMODELING", "ADDITIONS_CONSTRUCTION",
    "OUTDOOR_LIVING", "ACCESSIBILITY", "RESTORATION", "EXTERIOR",
    "HVAC", "PLUMBING", "PAINTING", "ROOFING",
  ],
  PLUMBING: [
    "PLUMBING", "GENERAL", "INTERIOR_REMODELING", "RESTORATION",
    "ACCESSIBILITY", "ADDITIONS_CONSTRUCTION", "HVAC", "EXTERIOR",
    "OUTDOOR_LIVING", "ELECTRICAL", "PAINTING", "ROOFING",
  ],
  HVAC: [
    "HVAC", "GENERAL", "ADDITIONS_CONSTRUCTION", "INTERIOR_REMODELING",
    "RESTORATION", "ACCESSIBILITY", "EXTERIOR", "ELECTRICAL",
    "PLUMBING", "ROOFING", "OUTDOOR_LIVING", "PAINTING",
  ],
  FLOORING: [
    "INTERIOR_REMODELING", "GENERAL", "PAINTING", "RESTORATION",
    "ACCESSIBILITY", "ADDITIONS_CONSTRUCTION", "OUTDOOR_LIVING", "EXTERIOR",
    "ROOFING", "PLUMBING", "ELECTRICAL", "HVAC",
  ],
  WINDOWS_DOORS: [
    "EXTERIOR", "INTERIOR_REMODELING", "GENERAL", "PAINTING",
    "RESTORATION", "ADDITIONS_CONSTRUCTION", "ACCESSIBILITY", "OUTDOOR_LIVING",
    "ROOFING", "ELECTRICAL", "PLUMBING", "HVAC",
  ],
  MASONRY: [
    "EXTERIOR", "OUTDOOR_LIVING", "ADDITIONS_CONSTRUCTION", "GENERAL",
    "RESTORATION", "INTERIOR_REMODELING", "PAINTING", "ROOFING",
    "ACCESSIBILITY", "PLUMBING", "ELECTRICAL", "HVAC",
  ],
  RESTORATION: [
    "RESTORATION", "GENERAL", "INTERIOR_REMODELING", "EXTERIOR",
    "ROOFING", "PAINTING", "PLUMBING", "ELECTRICAL",
    "HVAC", "ADDITIONS_CONSTRUCTION", "OUTDOOR_LIVING", "ACCESSIBILITY",
  ],
  ACCESSIBILITY_AGING_IN_PLACE: [
    "ACCESSIBILITY", "INTERIOR_REMODELING", "GENERAL", "PLUMBING",
    "ELECTRICAL", "PAINTING", "ADDITIONS_CONSTRUCTION", "EXTERIOR",
    "OUTDOOR_LIVING", "RESTORATION", "ROOFING", "HVAC",
  ],
  NEW_CONSTRUCTION: [
    "ADDITIONS_CONSTRUCTION", "INTERIOR_REMODELING", "EXTERIOR", "ROOFING",
    "OUTDOOR_LIVING", "PAINTING", "PLUMBING", "ELECTRICAL",
    "HVAC", "ACCESSIBILITY", "GENERAL", "RESTORATION",
  ],
  DESIGN_BUILD: [
    "INTERIOR_REMODELING", "ADDITIONS_CONSTRUCTION", "OUTDOOR_LIVING", "EXTERIOR",
    "ACCESSIBILITY", "RESTORATION", "PAINTING", "ROOFING",
    "PLUMBING", "ELECTRICAL", "HVAC", "GENERAL",
  ],
  PROPERTY_MAINTENANCE: [
    "GENERAL", "INTERIOR_REMODELING", "EXTERIOR", "PLUMBING",
    "ELECTRICAL", "PAINTING", "ROOFING", "HVAC",
    "OUTDOOR_LIVING", "RESTORATION", "ACCESSIBILITY", "ADDITIONS_CONSTRUCTION",
  ],
  OTHER: [...PROJECT_CATEGORY_KEYS],
};

/**
 * Top project-type recommendations per primary business type.
 * Kept short (<= 8 each) so downstream code can cap at 6 with room to
 * de-duplicate against specialties.
 */
export const BUSINESS_TYPE_RECOMMENDED_TYPES: Record<PrimaryBusinessType, readonly string[]> = {
  GENERAL_REMODELING: [
    "KITCHEN_REMODEL", "BATHROOM_REMODEL", "WHOLE_HOUSE_REMODEL",
    "BASEMENT_FINISH", "HOME_ADDITION", "FLOORING",
  ],
  HANDYMAN: [
    "GENERAL_REPAIR", "MAINTENANCE", "PUNCH_LIST",
    "DRYWALL_PLASTER", "FIXTURE_REPLACEMENT", "TV_MOUNTING",
    "CEILING_FAN_INSTALLATION", "SMALL_HOME_REPAIR",
  ],
  GENERAL_CONTRACTOR: [
    "WHOLE_HOUSE_REMODEL", "HOME_ADDITION", "NEW_CONSTRUCTION",
    "KITCHEN_REMODEL", "BATHROOM_REMODEL", "STRUCTURAL_REPAIR",
  ],
  KITCHEN_BATH: [
    "KITCHEN_REMODEL", "BATHROOM_REMODEL", "CABINETS_MILLWORK",
    "FIXTURE_REPLACEMENT", "ACCESSIBLE_BATHROOM", "FLOORING",
  ],
  PAINTING: [
    "INTERIOR_PAINTING", "EXTERIOR_PAINTING", "CABINET_PAINTING",
    "STAINING_FINISHING", "DRYWALL_PLASTER", "GENERAL_REPAIR",
  ],
  ROOFING: [
    "ROOF_REPLACEMENT", "ROOF_REPAIR", "METAL_ROOFING",
    "FLAT_LOW_SLOPE_ROOFING", "GUTTERS", "SIDING",
  ],
  EXTERIOR_CONTRACTOR: [
    "SIDING", "WINDOWS_DOORS", "GUTTERS",
    "EXTERIOR_PAINTING", "DECK_PORCH", "FENCING",
  ],
  DECKS_OUTDOOR_LIVING: [
    "DECK", "PERGOLA", "COVERED_PATIO",
    "OUTDOOR_KITCHEN", "SCREENED_PORCH", "FIRE_PIT_FIREPLACE",
  ],
  ELECTRICAL: [
    "ELECTRICAL_REPAIR", "LIGHTING", "OUTLET_SWITCH_INSTALLATION",
    "CEILING_FAN_INSTALLATION", "SERVICE_PANEL_UPGRADE", "GENERATOR_BACKUP_POWER",
  ],
  PLUMBING: [
    "PLUMBING_REPAIR", "FIXTURE_REPLACEMENT", "WATER_HEATER",
    "DRAIN_SEWER", "REPIPING",
  ],
  HVAC: ["HEATING", "COOLING", "HEAT_PUMP", "DUCTWORK", "VENTILATION"],
  FLOORING: ["FLOORING", "TRIM_FINISH_CARPENTRY", "STAIRS", "GENERAL_REPAIR"],
  WINDOWS_DOORS: [
    "WINDOWS_DOORS", "DOOR_INSTALLATION_REPAIR", "WINDOW_REPAIR",
    "CAULKING_WEATHERPROOFING", "EXTERIOR_PAINTING",
  ],
  MASONRY: [
    "MASONRY", "RETAINING_WALL", "FIRE_PIT_FIREPLACE",
    "PATIO", "STRUCTURAL_REPAIR",
  ],
  RESTORATION: [
    "WATER_DAMAGE", "MOLD_REMEDIATION", "FIRE_SMOKE_DAMAGE",
    "INSURANCE_REPAIR", "DRYWALL_PLASTER", "GENERAL_REPAIR",
  ],
  ACCESSIBILITY_AGING_IN_PLACE: [
    "ACCESSIBILITY_MODIFICATION", "AGING_IN_PLACE", "ACCESSIBLE_BATHROOM",
    "RAMP_LIFT", "GRAB_BAR_INSTALLATION", "FIXTURE_REPLACEMENT",
  ],
  NEW_CONSTRUCTION: [
    "NEW_CONSTRUCTION", "HOME_ADDITION", "ADU",
    "WHOLE_HOUSE_REMODEL", "STRUCTURAL_REPAIR",
  ],
  DESIGN_BUILD: [
    "WHOLE_HOUSE_REMODEL", "KITCHEN_REMODEL", "BATHROOM_REMODEL",
    "HOME_ADDITION", "OUTDOOR_KITCHEN", "SUNROOM",
  ],
  PROPERTY_MAINTENANCE: [
    "MAINTENANCE", "GENERAL_REPAIR", "RENTAL_TURNOVER",
    "PUNCH_LIST", "PRESSURE_WASHING", "INSPECTION_CONSULTATION",
  ],
  OTHER: [],
};

/**
 * Default recommended project scale by primary business type.
 * Used only as an initial suggestion; users can always override.
 */
export const DEFAULT_SCALE_BY_BUSINESS: Record<PrimaryBusinessType, ProjectScaleKey> = {
  GENERAL_REMODELING: "REMODEL",
  HANDYMAN: "HALF_DAY",
  GENERAL_CONTRACTOR: "MAJOR_RENOVATION",
  KITCHEN_BATH: "REMODEL",
  PAINTING: "MULTI_DAY_SMALL_PROJECT",
  ROOFING: "MULTI_DAY_SMALL_PROJECT",
  EXTERIOR_CONTRACTOR: "MULTI_DAY_SMALL_PROJECT",
  DECKS_OUTDOOR_LIVING: "MULTI_DAY_SMALL_PROJECT",
  ELECTRICAL: "FULL_DAY",
  PLUMBING: "HALF_DAY",
  HVAC: "FULL_DAY",
  FLOORING: "MULTI_DAY_SMALL_PROJECT",
  WINDOWS_DOORS: "FULL_DAY",
  MASONRY: "MULTI_DAY_SMALL_PROJECT",
  RESTORATION: "REMODEL",
  ACCESSIBILITY_AGING_IN_PLACE: "MULTI_DAY_SMALL_PROJECT",
  NEW_CONSTRUCTION: "NEW_CONSTRUCTION",
  DESIGN_BUILD: "MAJOR_RENOVATION",
  PROPERTY_MAINTENANCE: "QUICK_REPAIR",
  OTHER: "REMODEL",
};
