/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ProposalPrintProjectIdRouteImport } from './routes/proposal-print.$projectId'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as AppWalkthroughRouteImport } from './routes/app.walkthrough'
import { Route as AppTradeCoverageRouteImport } from './routes/app.trade-coverage'
import { Route as AppTerminologyRouteImport } from './routes/app.terminology'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRenderingsRouteImport } from './routes/app.renderings'
import { Route as AppRemoteVisionRouteImport } from './routes/app.remote-vision'
import { Route as AppProposalsRouteImport } from './routes/app.proposals'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrganizationRouteImport } from './routes/app.organization'
import { Route as AppKnowledgeBaseRouteImport } from './routes/app.knowledge-base'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppEstimatesRouteImport } from './routes/app.estimates'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCostBookRouteImport } from './routes/app.cost-book'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCaptureRouteImport } from './routes/app.capture'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppBallparkRouteImport } from './routes/app.ballpark'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppClientsIndexRouteImport } from './routes/app.clients.index'
import { Route as AppProposalProjectIdRouteImport } from './routes/app.proposal.$projectId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppClientsClientIdRouteImport } from './routes/app.clients.$clientId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app.projects.$projectId.index'
import { Route as AppClientsClientIdIndexRouteImport } from './routes/app.clients.$clientId.index'
import { Route as AppProjectsProjectIdRoomsRoomIdRouteImport } from './routes/app.projects.$projectId.rooms.$roomId'
import { Route as AppClientsClientIdPropertiesPropertyIdRouteImport } from './routes/app.clients.$clientId.properties.$propertyId'

const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ProposalPrintProjectIdRoute = ProposalPrintProjectIdRouteImport.update({
  id: '/proposal-print/$projectId',
  path: '/proposal-print/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalkthroughRoute = AppWalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeCoverageRoute = AppTradeCoverageRouteImport.update({
  id: '/trade-coverage',
  path: '/trade-coverage',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminologyRoute = AppTerminologyRouteImport.update({
  id: '/terminology',
  path: '/terminology',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRenderingsRoute = AppRenderingsRouteImport.update({
  id: '/renderings',
  path: '/renderings',
  getParentRoute: () => AppRoute,
} as any)
const AppRemoteVisionRoute = AppRemoteVisionRouteImport.update({
  id: '/remote-vision',
  path: '/remote-vision',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppEstimatesRoute = AppEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCostBookRoute = AppCostBookRouteImport.update({
  id: '/cost-book',
  path: '/cost-book',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBallparkRoute = AppBallparkRouteImport.update({
  id: '/ballpark',
  path: '/ballpark',
  getParentRoute: () => AppRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppProposalProjectIdRoute = AppProposalProjectIdRouteImport.update({
  id: '/proposal/$projectId',
  path: '/proposal/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppClientsClientIdIndexRoute = AppClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsClientIdRoute,
} as any)
const AppProjectsProjectIdRoomsRoomIdRoute =
  AppProjectsProjectIdRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppClientsClientIdPropertiesPropertyIdRoute =
  AppClientsClientIdPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system-status': typeof SystemStatusRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/app/ballpark': typeof AppBallparkRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/cost-book': typeof AppCostBookRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estimates': typeof AppEstimatesRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/properties': typeof AppPropertiesRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/remote-vision': typeof AppRemoteVisionRoute
  '/app/renderings': typeof AppRenderingsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/terminology': typeof AppTerminologyRoute
  '/app/trade-coverage': typeof AppTradeCoverageRoute
  '/app/walkthrough': typeof AppWalkthroughRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$token': typeof PTokenRoute
  '/proposal-print/$projectId': typeof ProposalPrintProjectIdRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/proposal/$projectId': typeof AppProposalProjectIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/clients/$clientId/properties/$propertyId': typeof AppClientsClientIdPropertiesPropertyIdRoute
  '/app/projects/$projectId/rooms/$roomId': typeof AppProjectsProjectIdRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system-status': typeof SystemStatusRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/app/ballpark': typeof AppBallparkRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/cost-book': typeof AppCostBookRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estimates': typeof AppEstimatesRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/remote-vision': typeof AppRemoteVisionRoute
  '/app/renderings': typeof AppRenderingsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/terminology': typeof AppTerminologyRoute
  '/app/trade-coverage': typeof AppTradeCoverageRoute
  '/app/walkthrough': typeof AppWalkthroughRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$token': typeof PTokenRoute
  '/proposal-print/$projectId': typeof ProposalPrintProjectIdRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/proposal/$projectId': typeof AppProposalProjectIdRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/clients/$clientId/properties/$propertyId': typeof AppClientsClientIdPropertiesPropertyIdRoute
  '/app/projects/$projectId/rooms/$roomId': typeof AppProjectsProjectIdRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system-status': typeof SystemStatusRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/app/ballpark': typeof AppBallparkRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/cost-book': typeof AppCostBookRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estimates': typeof AppEstimatesRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/properties': typeof AppPropertiesRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/remote-vision': typeof AppRemoteVisionRoute
  '/app/renderings': typeof AppRenderingsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/terminology': typeof AppTerminologyRoute
  '/app/trade-coverage': typeof AppTradeCoverageRoute
  '/app/walkthrough': typeof AppWalkthroughRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$token': typeof PTokenRoute
  '/proposal-print/$projectId': typeof ProposalPrintProjectIdRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/proposal/$projectId': typeof AppProposalProjectIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/clients/$clientId/properties/$propertyId': typeof AppClientsClientIdPropertiesPropertyIdRoute
  '/app/projects/$projectId/rooms/$roomId': typeof AppProjectsProjectIdRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/no-access'
    | '/register'
    | '/reset-password'
    | '/system-status'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/transcribe'
    | '/app/ballpark'
    | '/app/billing'
    | '/app/calendar'
    | '/app/capture'
    | '/app/clients'
    | '/app/cost-book'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/estimates'
    | '/app/files'
    | '/app/knowledge'
    | '/app/knowledge-base'
    | '/app/organization'
    | '/app/profile'
    | '/app/projects'
    | '/app/properties'
    | '/app/proposals'
    | '/app/remote-vision'
    | '/app/renderings'
    | '/app/reports'
    | '/app/settings'
    | '/app/support'
    | '/app/terminology'
    | '/app/trade-coverage'
    | '/app/walkthrough'
    | '/legal/privacy'
    | '/legal/terms'
    | '/p/$token'
    | '/proposal-print/$projectId'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/stripe-webhook'
    | '/app/clients/$clientId'
    | '/app/projects/$projectId'
    | '/app/proposal/$projectId'
    | '/app/clients/'
    | '/app/projects/'
    | '/app/clients/$clientId/'
    | '/app/projects/$projectId/'
    | '/app/clients/$clientId/properties/$propertyId'
    | '/app/projects/$projectId/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/no-access'
    | '/register'
    | '/reset-password'
    | '/system-status'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/transcribe'
    | '/app/ballpark'
    | '/app/billing'
    | '/app/calendar'
    | '/app/capture'
    | '/app/cost-book'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/estimates'
    | '/app/files'
    | '/app/knowledge'
    | '/app/knowledge-base'
    | '/app/organization'
    | '/app/profile'
    | '/app/properties'
    | '/app/proposals'
    | '/app/remote-vision'
    | '/app/renderings'
    | '/app/reports'
    | '/app/settings'
    | '/app/support'
    | '/app/terminology'
    | '/app/trade-coverage'
    | '/app/walkthrough'
    | '/legal/privacy'
    | '/legal/terms'
    | '/p/$token'
    | '/proposal-print/$projectId'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/stripe-webhook'
    | '/app/proposal/$projectId'
    | '/app/clients'
    | '/app/projects'
    | '/app/clients/$clientId'
    | '/app/projects/$projectId'
    | '/app/clients/$clientId/properties/$propertyId'
    | '/app/projects/$projectId/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/no-access'
    | '/register'
    | '/reset-password'
    | '/system-status'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/transcribe'
    | '/app/ballpark'
    | '/app/billing'
    | '/app/calendar'
    | '/app/capture'
    | '/app/clients'
    | '/app/cost-book'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/estimates'
    | '/app/files'
    | '/app/knowledge'
    | '/app/knowledge-base'
    | '/app/organization'
    | '/app/profile'
    | '/app/projects'
    | '/app/properties'
    | '/app/proposals'
    | '/app/remote-vision'
    | '/app/renderings'
    | '/app/reports'
    | '/app/settings'
    | '/app/support'
    | '/app/terminology'
    | '/app/trade-coverage'
    | '/app/walkthrough'
    | '/legal/privacy'
    | '/legal/terms'
    | '/p/$token'
    | '/proposal-print/$projectId'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/stripe-webhook'
    | '/app/clients/$clientId'
    | '/app/projects/$projectId'
    | '/app/proposal/$projectId'
    | '/app/clients/'
    | '/app/projects/'
    | '/app/clients/$clientId/'
    | '/app/projects/$projectId/'
    | '/app/clients/$clientId/properties/$propertyId'
    | '/app/projects/$projectId/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  NoAccessRoute: typeof NoAccessRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SystemStatusRoute: typeof SystemStatusRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PTokenRoute: typeof PTokenRoute
  ProposalPrintProjectIdRoute: typeof ProposalPrintProjectIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/proposal-print/$projectId': {
      id: '/proposal-print/$projectId'
      path: '/proposal-print/$projectId'
      fullPath: '/proposal-print/$projectId'
      preLoaderRoute: typeof ProposalPrintProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/walkthrough': {
      id: '/app/walkthrough'
      path: '/walkthrough'
      fullPath: '/app/walkthrough'
      preLoaderRoute: typeof AppWalkthroughRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trade-coverage': {
      id: '/app/trade-coverage'
      path: '/trade-coverage'
      fullPath: '/app/trade-coverage'
      preLoaderRoute: typeof AppTradeCoverageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terminology': {
      id: '/app/terminology'
      path: '/terminology'
      fullPath: '/app/terminology'
      preLoaderRoute: typeof AppTerminologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/renderings': {
      id: '/app/renderings'
      path: '/renderings'
      fullPath: '/app/renderings'
      preLoaderRoute: typeof AppRenderingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/remote-vision': {
      id: '/app/remote-vision'
      path: '/remote-vision'
      fullPath: '/app/remote-vision'
      preLoaderRoute: typeof AppRemoteVisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proposals': {
      id: '/app/proposals'
      path: '/proposals'
      fullPath: '/app/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge-base': {
      id: '/app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/app/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estimates': {
      id: '/app/estimates'
      path: '/estimates'
      fullPath: '/app/estimates'
      preLoaderRoute: typeof AppEstimatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cost-book': {
      id: '/app/cost-book'
      path: '/cost-book'
      fullPath: '/app/cost-book'
      preLoaderRoute: typeof AppCostBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/capture': {
      id: '/app/capture'
      path: '/capture'
      fullPath: '/app/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ballpark': {
      id: '/app/ballpark'
      path: '/ballpark'
      fullPath: '/app/ballpark'
      preLoaderRoute: typeof AppBallparkRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/proposal/$projectId': {
      id: '/app/proposal/$projectId'
      path: '/proposal/$projectId'
      fullPath: '/app/proposal/$projectId'
      preLoaderRoute: typeof AppProposalProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/clients/$clientId/': {
      id: '/app/clients/$clientId/'
      path: '/'
      fullPath: '/app/clients/$clientId/'
      preLoaderRoute: typeof AppClientsClientIdIndexRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/app/projects/$projectId/rooms/$roomId': {
      id: '/app/projects/$projectId/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/app/projects/$projectId/rooms/$roomId'
      preLoaderRoute: typeof AppProjectsProjectIdRoomsRoomIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/clients/$clientId/properties/$propertyId': {
      id: '/app/clients/$clientId/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/app/clients/$clientId/properties/$propertyId'
      preLoaderRoute: typeof AppClientsClientIdPropertiesPropertyIdRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
  }
}

interface AppClientsClientIdRouteChildren {
  AppClientsClientIdIndexRoute: typeof AppClientsClientIdIndexRoute
  AppClientsClientIdPropertiesPropertyIdRoute: typeof AppClientsClientIdPropertiesPropertyIdRoute
}

const AppClientsClientIdRouteChildren: AppClientsClientIdRouteChildren = {
  AppClientsClientIdIndexRoute: AppClientsClientIdIndexRoute,
  AppClientsClientIdPropertiesPropertyIdRoute:
    AppClientsClientIdPropertiesPropertyIdRoute,
}

const AppClientsClientIdRouteWithChildren =
  AppClientsClientIdRoute._addFileChildren(AppClientsClientIdRouteChildren)

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRouteWithChildren
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRouteWithChildren,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdRoomsRoomIdRoute: typeof AppProjectsProjectIdRoomsRoomIdRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdRoomsRoomIdRoute: AppProjectsProjectIdRoomsRoomIdRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppBallparkRoute: typeof AppBallparkRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCaptureRoute: typeof AppCaptureRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppCostBookRoute: typeof AppCostBookRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstimatesRoute: typeof AppEstimatesRoute
  AppFilesRoute: typeof AppFilesRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppPropertiesRoute: typeof AppPropertiesRoute
  AppProposalsRoute: typeof AppProposalsRoute
  AppRemoteVisionRoute: typeof AppRemoteVisionRoute
  AppRenderingsRoute: typeof AppRenderingsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTerminologyRoute: typeof AppTerminologyRoute
  AppTradeCoverageRoute: typeof AppTradeCoverageRoute
  AppWalkthroughRoute: typeof AppWalkthroughRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProposalProjectIdRoute: typeof AppProposalProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBallparkRoute: AppBallparkRoute,
  AppBillingRoute: AppBillingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCaptureRoute: AppCaptureRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppCostBookRoute: AppCostBookRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstimatesRoute: AppEstimatesRoute,
  AppFilesRoute: AppFilesRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppPropertiesRoute: AppPropertiesRoute,
  AppProposalsRoute: AppProposalsRoute,
  AppRemoteVisionRoute: AppRemoteVisionRoute,
  AppRenderingsRoute: AppRenderingsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTerminologyRoute: AppTerminologyRoute,
  AppTradeCoverageRoute: AppTradeCoverageRoute,
  AppWalkthroughRoute: AppWalkthroughRoute,
  AppIndexRoute: AppIndexRoute,
  AppProposalProjectIdRoute: AppProposalProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  NoAccessRoute: NoAccessRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SystemStatusRoute: SystemStatusRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PTokenRoute: PTokenRoute,
  ProposalPrintProjectIdRoute: ProposalPrintProjectIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
