import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import type { NarrativeQuestion } from "@/domains/narrativeScope";

interface Props {
  /** Unanswered questions (first-time or newly generated by scope changes). */
  questions: NarrativeQuestion[];
  /** Previously answered questions, restored for review/revision. */
  answeredQuestions?: NarrativeQuestion[];
  answers: Record<string, string>;
  onSave: (answers: Record<string, string>) => void;
  onClose: () => void;
}

export function NarrativeQuestionsPanel({
  questions,
  answeredQuestions = [],
  answers,
  onSave,
  onClose,
}: Props) {
  const { t } = useTranslation("narrative");
  const [draft, setDraft] = useState<Record<string, string>>(answers);

  const renderQuestion = (q: NarrativeQuestion) => (
    <li key={q.id} className="space-y-2 rounded-lg border border-border p-4">
      <p className="text-sm font-medium">{t(q.promptKey, { subject: q.subject.toLowerCase() })}</p>
      {q.options.length > 0 ? (
        <div className="flex flex-wrap gap-2">
          {q.options.map((option) => {
                  const label = t(option.labelKey);
                  return (
                    <Button
                      key={option.value}
                      type="button"
                      size="sm"
                      variant={draft[q.id] === label ? "default" : "outline"}
                      className="min-h-(--control-min-h)"
                      onClick={() => setDraft((prev) => ({ ...prev, [q.id]: label }))}
                    >
                      {label}
                    </Button>
                  );
                })}
              </div>
            ) : null}
            {q.answerType === "text" ? (
              <Input
                className="min-h-(--control-min-h)"
                placeholder={t("questions.placeholder")}
                value={draft[q.id] ?? ""}
                onChange={(e) => setDraft((prev) => ({ ...prev, [q.id]: e.target.value }))}
        />
      ) : null}
    </li>
  );

  if (questions.length === 0 && answeredQuestions.length === 0) {
    return (
      <Card>
        <CardContent className="space-y-4 p-5 text-center">
          <p className="text-sm text-foreground-muted" data-testid="scope-questions-none">
            {t("questions.none")}
          </p>
          <Button className="min-h-(--control-min-h) w-full" onClick={onClose}>
            {t("actions.cancel")}
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-base font-semibold">
          {questions.length > 0 && answeredQuestions.length > 0
            ? t("questions.newTitle", { count: questions.length })
            : questions.length > 0
              ? t("questions.title")
              : t("questions.reviewTitle")}
        </h3>
        <p className="text-sm text-foreground-muted">
          {questions.length > 0 ? t("questions.hint") : t("questions.reviewHint")}
        </p>
      </div>

      {questions.length > 0 ? (
        <ul className="space-y-3" data-testid="scope-questions-new">
          {questions.map(renderQuestion)}
        </ul>
      ) : null}

      {answeredQuestions.length > 0 ? (
        <div className="space-y-3" data-testid="scope-questions-answered">
          {questions.length > 0 ? (
            <p className="text-sm font-medium text-foreground-muted">
              {t("questions.answeredTitle")}
            </p>
          ) : null}
          <ul className="space-y-3">{answeredQuestions.map(renderQuestion)}</ul>
        </div>
      ) : null}

      <div className="grid gap-2 sm:grid-cols-2">
        <Button className="min-h-(--control-min-h)" onClick={() => onSave(draft)}>
          {t("questions.save")}
        </Button>
        <Button className="min-h-(--control-min-h)" variant="outline" onClick={onClose}>
          {t("actions.cancel")}
        </Button>
      </div>
    </div>
  );
}
