/**
 * Residential Core intent map — Library v2 additions.
 *
 * Same contract as `intentMap.ts` (see that file's header): a deterministic
 * phrase → assembly / composite / review map that ranks ABOVE fuzzy text
 * overlap. These rules exist so obvious residential wording resolves to the
 * semantically correct trade instead of the nearest-looking catalog string.
 *
 * Authoring rules enforced by `src/tests/estimating/matcherMatrix.test.ts`:
 *  - the ACTION verb decides the trade ("paint cabinets" is Painting,
 *    "install cabinets" is Cabinetry);
 *  - a plural / bundled phrase must map to a labelled composite allowance or a
 *    review outcome — never to one atomic unit;
 *  - adjectives ("mid-grade", "paint-grade", "countertop level") must not
 *    create scope, so no rule may key on them.
 *
 * Pure data — no React, no Supabase, no IO.
 */
import type { IntentRule } from "./intentMap";

const one = (assemblyKey: string, role: string) => [{ assemblyKey, quantityFactor: 1, role }];

export const INTENT_RULES_V2: IntentRule[] = [
  /* ---------------- general conditions ---------------- */
  { phrase: "mobilization", matchKind: "contains", components: one("gc.mobilization.crew", "mobilization") },
  { phrase: "site protection", matchKind: "contains", components: one("gc.protection.floorpath", "protection") },
  { phrase: "protect floors", matchKind: "contains", components: one("gc.protection.floorpath", "floor protection") },
  { phrase: "dust containment", matchKind: "contains", components: one("gc.protection.dustwall", "dust barrier") },
  { phrase: "dust barrier", matchKind: "contains", components: one("gc.protection.dustwall", "dust barrier") },
  { phrase: "final clean", matchKind: "contains", components: one("gc.cleanup.final", "final cleaning") },
  { phrase: "final cleaning", matchKind: "contains", components: one("gc.cleanup.final", "final cleaning") },
  { phrase: "daily cleanup", matchKind: "contains", components: one("gc.cleanup.daily", "daily cleanup") },
  { phrase: "dumpster", matchKind: "contains", priority: 80, components: one("gc.dumpster.20yd", "dumpster") },
  { phrase: "roll off", matchKind: "contains", components: one("gc.dumpster.20yd", "dumpster") },
  { phrase: "portable toilet", matchKind: "contains", components: one("gc.portable.toilet", "sanitation") },
  { phrase: "equipment rental", matchKind: "contains", components: one("gc.equipment.rental", "equipment rental") },
  { phrase: "temporary power", matchKind: "contains", components: one("gc.temp.power", "temporary power") },
  { phrase: "service call minimum", matchKind: "contains", components: one("gc.servicecall.minimum", "small-job minimum") },
  { phrase: "trip charge", matchKind: "contains", components: one("gc.servicecall.minimum", "small-job minimum") },
  { phrase: "demolition permit", matchKind: "contains", components: one("permits.demolition.fee", "permit fee") },
  { phrase: "roofing permit", matchKind: "contains", components: one("permits.roofing.fee", "permit fee") },
  { phrase: "plan review", matchKind: "contains", components: one("permits.plan.review", "plan review fee") },

  /* ---------------- demolition ---------------- */
  { phrase: "demo ceiling drywall", matchKind: "contains", components: one("demo.ceiling.drywall", "ceiling demo") },
  { phrase: "remove plaster", matchKind: "contains", components: one("demo.plaster.walls", "plaster demo") },
  { phrase: "remove sheet vinyl", matchKind: "contains", components: one("demo.flooring.vinyl", "vinyl demo") },
  { phrase: "remove laminate flooring", matchKind: "contains", components: one("demo.flooring.laminate", "laminate demo") },
  { phrase: "remove wall tile", matchKind: "contains", components: one("demo.tile.wall", "wall tile demo") },
  { phrase: "demo shower tile", matchKind: "contains", components: one("demo.tile.wall", "shower tile demo") },
  { phrase: "remove countertops", matchKind: "contains", priority: 92, components: one("demo.countertop.remove", "countertop demo") },
  { phrase: "remove vanity", matchKind: "contains", components: one("demo.vanity.remove", "vanity demo") },
  { phrase: "remove toilet", matchKind: "contains", components: one("demo.toilet.remove", "toilet demo") },
  { phrase: "remove window", matchKind: "contains", priority: 88, components: one("demo.window.remove", "window demo") },
  { phrase: "remove drop ceiling", matchKind: "contains", components: one("demo.ceiling.acoustic", "acoustic ceiling demo") },
  { phrase: "selective demolition", matchKind: "contains", components: one("demo.selective.interior", "selective demo") },
  { phrase: "remove subfloor", matchKind: "contains", components: one("demo.subfloor.remove", "subfloor demo") },
  { phrase: "tear off roof", matchKind: "contains", components: one("demo.roof.tearoff", "roof tear-off") },
  { phrase: "roof tear off", matchKind: "contains", components: one("demo.roof.tearoff", "roof tear-off") },
  { phrase: "remove siding", matchKind: "contains", components: one("demo.siding.remove", "siding demo") },
  { phrase: "remove existing deck", matchKind: "contains", components: one("demo.deck.remove", "deck demo") },
  { phrase: "break out concrete", matchKind: "contains", components: one("demo.concrete.slab", "concrete demo") },
  { phrase: "remove fence", matchKind: "contains", components: one("demo.fence.remove", "fence demo") },

  /* ---------------- framing ---------------- */
  { phrase: "frame interior partition", matchKind: "contains", priority: 95, components: one("framing.wall.partition.2x4", "partition framing") },
  { phrase: "frame partition wall", matchKind: "contains", priority: 95, components: one("framing.wall.partition.2x4", "partition framing") },
  { phrase: "frame 2x6 wall", matchKind: "contains", components: one("framing.wall.partition.2x6", "partition framing") },
  { phrase: "knee wall", matchKind: "contains", components: one("framing.wall.knee", "knee wall framing") },
  { phrase: "build soffit", matchKind: "contains", components: one("framing.soffit.build", "soffit framing") },
  { phrase: "bulkhead", matchKind: "contains", priority: 70, components: one("framing.soffit.build", "bulkhead framing") },
  { phrase: "furring strips", matchKind: "contains", components: one("framing.furring.wall", "furring") },
  { phrase: "platform floor", matchKind: "contains", components: one("framing.floor.platform", "platform framing") },
  { phrase: "sister joists", matchKind: "contains", components: one("framing.floor.sister", "joist reinforcement") },
  { phrase: "replace subfloor", matchKind: "contains", components: one("framing.subfloor.replace", "subfloor replacement") },
  { phrase: "flush beam", matchKind: "contains", components: one("framing.beam.flush", "structural beam") },
  { phrase: "steel column", matchKind: "contains", components: one("framing.column.steel", "steel column") },
  { phrase: "enlarge opening", matchKind: "contains", components: one("framing.opening.enlarge", "opening enlargement") },
  { phrase: "frame stairs", matchKind: "contains", components: one("framing.stair.build", "stair framing") },
  { phrase: "frame dormer", matchKind: "contains", components: one("framing.roof.dormer", "dormer framing") },
  { phrase: "wall sheathing", matchKind: "contains", components: one("framing.sheathing.wall", "sheathing") },

  /* ---------------- drywall ---------------- */
  { phrase: "hang drywall", matchKind: "contains", components: one("drywall.hang.walls", "board walls") },
  { phrase: "hang and finish drywall", matchKind: "contains", priority: 95, components: [
    { assemblyKey: "drywall.hang.walls", quantityFactor: 1, role: "board" },
    { assemblyKey: "drywall.finish.level4", quantityFactor: 1, role: "tape and finish" },
  ] },
  { phrase: "drywall ceilings", matchKind: "contains", components: one("drywall.hang.ceiling", "ceiling board") },
  { phrase: "cement board", matchKind: "contains", components: one("drywall.hang.cementboard", "backer board") },
  { phrase: "backer board", matchKind: "contains", components: one("drywall.hang.cementboard", "backer board") },
  { phrase: "level 5 finish", matchKind: "contains", components: one("drywall.finish.level5", "level 5 finish") },
  { phrase: "tape and finish", matchKind: "contains", components: one("drywall.finish.level4", "tape and finish") },
  { phrase: "skim coat", matchKind: "contains", components: one("drywall.skimcoat.walls", "skim coat") },
  { phrase: "knockdown texture", matchKind: "contains", components: one("drywall.texture.knockdown", "texture") },
  { phrase: "corner bead", matchKind: "contains", components: one("drywall.cornerbead.install", "corner bead") },
  { phrase: "patch drywall hole", matchKind: "contains", components: one("drywall.patch.small", "drywall patch") },
  { phrase: "small drywall patch", matchKind: "contains", components: one("drywall.patch.small", "drywall patch") },
  { phrase: "drywall patch", matchKind: "contains", priority: 85, components: one("drywall.patch.medium", "drywall patch") },
  { phrase: "ceiling repair", matchKind: "contains", components: one("drywall.ceiling.repair", "ceiling repair") },
  { phrase: "plaster repair", matchKind: "contains", components: one("drywall.plaster.repair", "plaster repair") },

  /* ---------------- painting (action verb wins) ---------------- */
  { phrase: "prime and paint ceilings", matchKind: "contains", priority: 95, components: [
    { assemblyKey: "painting.prime.ceiling", quantityFactor: 1, role: "primer" },
    { assemblyKey: "painting.ceiling.twocoat", quantityFactor: 1, role: "ceiling finish" },
  ] },
  { phrase: "paint ceilings", matchKind: "contains", components: one("painting.ceiling.twocoat", "ceiling paint") },
  { phrase: "paint ceiling", matchKind: "contains", components: one("painting.ceiling.twocoat", "ceiling paint") },
  { phrase: "repaint walls", matchKind: "contains", components: one("painting.walls.onecoat", "wall refresh") },
  { phrase: "accent wall", matchKind: "contains", components: one("painting.accent.wall", "accent wall") },
  { phrase: "paint trim", matchKind: "contains", priority: 95, components: one("painting.trim.casing", "trim paint") },
  { phrase: "paint casing", matchKind: "contains", priority: 95, components: one("painting.trim.casing", "trim paint") },
  { phrase: "paint baseboard", matchKind: "contains", priority: 96, components: one("painting.trim.casing", "trim paint") },
  { phrase: "paint doors", matchKind: "contains", priority: 95, components: one("painting.door.each", "door paint") },
  { phrase: "paint door", matchKind: "contains", priority: 94, components: one("painting.door.each", "door paint") },
  { phrase: "paint cabinets", matchKind: "contains", priority: 96, components: one("painting.cabinets.spray", "cabinet painting") },
  { phrase: "paint kitchen cabinets", matchKind: "contains", priority: 97, components: one("painting.cabinets.spray", "cabinet painting") },
  { phrase: "refinish cabinets", matchKind: "contains", priority: 95, components: one("painting.cabinets.spray", "cabinet refinishing") },
  { phrase: "stain trim", matchKind: "contains", components: one("painting.stain.trim", "trim stain") },
  { phrase: "paint prep", matchKind: "contains", components: one("painting.prep.patchsand", "paint prep") },
  { phrase: "paint exterior siding", matchKind: "contains", priority: 95, components: one("painting.exterior.siding", "exterior paint") },
  { phrase: "exterior painting", matchKind: "contains", components: one("painting.exterior.siding", "exterior paint") },
  { phrase: "paint exterior trim", matchKind: "contains", priority: 95, components: one("painting.exterior.trim", "exterior trim paint") },
  { phrase: "stain deck", matchKind: "contains", components: one("painting.deck.stain", "deck stain") },
  { phrase: "power wash and prep", matchKind: "contains", components: one("painting.exterior.prep", "exterior prep") },
  { phrase: "paint railing", matchKind: "contains", components: one("painting.stairs.railing", "railing finish") },

  /* ---------------- flooring ---------------- */
  { phrase: "install lvp", matchKind: "contains", priority: 95, components: one("flooring.lvp.install", "LVP") },
  { phrase: "install luxury vinyl plank", matchKind: "contains", priority: 95, components: one("flooring.lvp.install", "LVP") },
  { phrase: "install vinyl plank", matchKind: "contains", components: one("flooring.lvp.install", "LVP") },
  { phrase: "lvp", matchKind: "contains", priority: 60, components: one("flooring.lvp.install", "LVP") },
  { phrase: "vinyl plank", matchKind: "contains", priority: 70, components: one("flooring.lvp.install", "LVP") },
  { phrase: "install laminate flooring", matchKind: "contains", components: one("flooring.laminate.install", "laminate") },
  { phrase: "install hardwood flooring", matchKind: "contains", priority: 95, components: one("flooring.hardwood.solid", "hardwood") },
  { phrase: "install engineered hardwood", matchKind: "contains", priority: 96, components: one("flooring.hardwood.engineered", "engineered hardwood") },
  { phrase: "install carpet", matchKind: "contains", components: one("flooring.carpet.install", "carpet and pad") },
  { phrase: "install sheet vinyl", matchKind: "contains", components: one("flooring.vinyl.sheet", "sheet vinyl") },
  { phrase: "install underlayment", matchKind: "contains", components: one("flooring.underlayment.install", "underlayment") },
  { phrase: "self leveling", matchKind: "contains", components: one("flooring.prep.selflevel", "floor levelling") },
  { phrase: "self-leveling", matchKind: "contains", components: one("flooring.prep.selflevel", "floor levelling") },
  { phrase: "grind slab", matchKind: "contains", components: one("flooring.prep.grind", "slab prep") },
  { phrase: "refinish hardwood", matchKind: "contains", priority: 95, components: one("flooring.refinish.sand", "sand and refinish") },
  { phrase: "sand and refinish floors", matchKind: "contains", components: one("flooring.refinish.sand", "sand and refinish") },
  { phrase: "stair treads", matchKind: "contains", components: one("flooring.stair.treads", "treads and risers") },

  /* ---------------- tile (never borrows room floor area) ---------------- */
  { phrase: "shower wall tile", matchKind: "contains", priority: 96, components: one("tile.shower.wall", "shower wall tile") },
  { phrase: "shower tile", matchKind: "contains", priority: 94, components: one("tile.shower.wall", "shower wall tile"),
    note: "Priced from the shower's own tiled area — room floor area is not valid evidence for shower tile." },
  { phrase: "shower floor tile", matchKind: "contains", priority: 97, components: one("tile.shower.floor", "shower floor tile") },
  { phrase: "bathroom floor tile", matchKind: "contains", priority: 95, components: one("tile.bath.floor", "bath floor tile") },
  { phrase: "install backsplash", matchKind: "contains", priority: 95, components: one("tile.backsplash.kitchen", "backsplash") },
  { phrase: "backsplash tile", matchKind: "contains", priority: 95, components: one("tile.backsplash.kitchen", "backsplash") },
  { phrase: "waterproof shower", matchKind: "contains", components: one("tile.waterproof.membrane", "waterproofing") },
  { phrase: "waterproofing membrane", matchKind: "contains", components: one("tile.waterproof.membrane", "waterproofing") },
  { phrase: "mud pan", matchKind: "contains", components: one("tile.shower.pan.mud", "shower pan") },
  { phrase: "shower pan", matchKind: "contains", priority: 88, components: one("tile.shower.pan.mud", "shower pan") },
  { phrase: "shower curb", matchKind: "contains", components: one("tile.shower.curb", "curb") },
  { phrase: "grout and seal", matchKind: "contains", components: one("tile.grout.seal", "grout and seal") },
  { phrase: "tile edge trim", matchKind: "contains", components: one("tile.schluter.trim", "edge profile") },
  { phrase: "heated floor", matchKind: "contains", components: one("tile.floor.heat", "floor heat") },
  { phrase: "tile bathroom", matchKind: "contains", priority: 70, review: "ambiguous_multi_scope",
    note: "Split the tile scope into shower walls, shower floor and bathroom floor — each is measured separately." },

  /* ---------------- plumbing ---------------- */
  { phrase: "install shutoffs and supply lines", matchKind: "contains", priority: 97,
    components: [
      { assemblyKey: "plumbing.shutoff.angle", quantityFactor: 1, role: "angle stops" },
      { assemblyKey: "plumbing.supply.line", quantityFactor: 1, role: "supply lines" },
    ],
    note: "Decomposed into stops and supply lines — confirm the fixture count; one valve is not the whole scope." },
  { phrase: "shutoffs and supply lines", matchKind: "contains", priority: 96,
    components: [
      { assemblyKey: "plumbing.shutoff.angle", quantityFactor: 1, role: "angle stops" },
      { assemblyKey: "plumbing.supply.line", quantityFactor: 1, role: "supply lines" },
    ] },
  { phrase: "bathroom plumbing connections", matchKind: "contains",
    components: one("plumbing.bath.connections.allowance", "bathroom connection allowance") },
  { phrase: "hook up fixtures", matchKind: "contains",
    components: one("plumbing.bath.connections.allowance", "fixture connection allowance") },
  { phrase: "kitchen plumbing", matchKind: "contains",
    components: one("plumbing.kitchen.connections.allowance", "kitchen connection allowance") },
  { phrase: "angle stop", matchKind: "contains", components: one("plumbing.shutoff.angle", "angle stop") },
  { phrase: "set toilet", matchKind: "contains", components: one("plumbing.toilet.set", "toilet") },
  { phrase: "install toilet", matchKind: "contains", components: one("plumbing.toilet.set", "toilet") },
  { phrase: "install lavatory", matchKind: "contains", components: one("plumbing.lav.set", "lavatory") },
  { phrase: "install bathroom sink", matchKind: "contains", components: one("plumbing.lav.set", "lavatory") },
  { phrase: "install kitchen sink", matchKind: "contains", priority: 95, components: one("plumbing.kitchen.sink", "kitchen sink") },
  { phrase: "replace faucet", matchKind: "contains", components: one("plumbing.faucet.replace", "faucet") },
  { phrase: "install faucet", matchKind: "contains", components: one("plumbing.faucet.replace", "faucet") },
  { phrase: "garbage disposal", matchKind: "contains", components: one("plumbing.disposal.install", "disposal") },
  { phrase: "dishwasher connection", matchKind: "contains", components: one("plumbing.dishwasher.connect", "dishwasher hookup") },
  { phrase: "set tub", matchKind: "contains", components: one("plumbing.tub.set", "bathtub") },
  { phrase: "install bathtub", matchKind: "contains", components: one("plumbing.tub.set", "bathtub") },
  { phrase: "shower valve", matchKind: "contains", priority: 90, components: one("plumbing.shower.valve", "shower valve") },
  { phrase: "shower head", matchKind: "contains", components: one("plumbing.showerhead.install", "shower head") },
  { phrase: "hose bib", matchKind: "contains", components: one("plumbing.hosebib.install", "hose bib") },
  { phrase: "laundry hookup", matchKind: "contains", components: one("plumbing.laundry.box", "laundry box") },
  { phrase: "water heater", matchKind: "contains", priority: 85, components: one("plumbing.waterheater.tank", "water heater") },
  { phrase: "tankless water heater", matchKind: "contains", priority: 95, components: one("plumbing.waterheater.tankless", "tankless heater") },
  { phrase: "drain waste and vent", matchKind: "contains", components: one("plumbing.dwv.rough", "DWV rough-in") },
  { phrase: "dwv rough", matchKind: "contains", components: one("plumbing.dwv.rough", "DWV rough-in") },
  { phrase: "water rough in", matchKind: "contains", components: one("plumbing.water.rough", "water rough-in") },
  { phrase: "relocate plumbing", matchKind: "contains", components: one("plumbing.fixture.relocate", "fixture relocation") },
  { phrase: "gas line", matchKind: "contains", components: one("plumbing.gas.line", "gas line") },

  /* ---------------- electrical ---------------- */
  { phrase: "new circuits, outlets, lighting", matchKind: "contains", priority: 120,
    components: one("electrical.room.package.allowance", "room electrical allowance"),
    note: "Bundled electrical scope priced as a disclosed room package allowance — confirm device and circuit counts for the detailed estimate." },
  { phrase: "circuits outlets and lighting", matchKind: "contains", priority: 118,
    components: one("electrical.room.package.allowance", "room electrical allowance") },
  { phrase: "outlets and lighting", matchKind: "contains", priority: 90,
    components: one("electrical.room.package.allowance", "room electrical allowance") },
  { phrase: "bathroom electrical", matchKind: "contains", components: one("electrical.bath.package.allowance", "bath electrical allowance") },
  { phrase: "kitchen electrical", matchKind: "contains", components: one("electrical.kitchen.package.allowance", "kitchen electrical allowance") },
  { phrase: "install receptacle", matchKind: "contains", components: one("electrical.receptacle.standard", "receptacle") },
  { phrase: "install outlet", matchKind: "contains", components: one("electrical.receptacle.standard", "receptacle") },
  { phrase: "gfci receptacle", matchKind: "contains", priority: 60, components: one("electrical.receptacle.gfci", "GFCI receptacle") },
  { phrase: "install switch", matchKind: "contains", components: one("electrical.switch.single", "switch") },
  { phrase: "dimmer", matchKind: "contains", priority: 85, components: one("electrical.switch.dimmer", "dimmer") },
  { phrase: "smoke detector", matchKind: "contains", components: one("electrical.smoke.co", "smoke/CO detector") },
  { phrase: "recessed lighting", matchKind: "contains", priority: 95, components: one("electrical.light.recessed", "recessed lights") },
  { phrase: "can lights", matchKind: "contains", components: one("electrical.light.recessed", "recessed lights") },
  { phrase: "install light fixture", matchKind: "contains", components: one("electrical.light.surface", "light fixture") },
  { phrase: "vanity light", matchKind: "contains", components: one("electrical.light.vanity", "vanity light") },
  { phrase: "ceiling fan", matchKind: "contains", components: one("electrical.fan.ceiling", "ceiling fan") },
  { phrase: "under cabinet lighting", matchKind: "contains", priority: 97, components: one("electrical.light.undercabinet", "under-cabinet lighting") },
  { phrase: "under-cabinet lighting", matchKind: "contains", priority: 97, components: one("electrical.light.undercabinet", "under-cabinet lighting") },
  { phrase: "exterior light", matchKind: "contains", components: one("electrical.light.exterior", "exterior fixture") },
  { phrase: "new circuit", matchKind: "contains", priority: 88, components: one("electrical.circuit.new", "branch circuit") },
  { phrase: "appliance circuit", matchKind: "contains", components: one("electrical.circuit.appliance", "appliance circuit") },
  { phrase: "extend circuit", matchKind: "contains", components: one("electrical.circuit.extend", "circuit extension") },
  { phrase: "subpanel", matchKind: "contains", components: one("electrical.panel.subpanel", "subpanel") },
  { phrase: "panel upgrade", matchKind: "contains", components: one("electrical.panel.upgrade", "service upgrade") },
  { phrase: "low voltage", matchKind: "contains", components: one("electrical.lowvoltage.run", "low-voltage drop") },

  /* ---------------- HVAC ---------------- */
  { phrase: "extend supply duct", matchKind: "contains", components: one("hvac.supply.extend", "supply run") },
  { phrase: "add return air", matchKind: "contains", components: one("hvac.return.add", "return drop") },
  { phrase: "relocate register", matchKind: "contains", components: one("hvac.register.relocate", "register relocation") },
  { phrase: "duct modification", matchKind: "contains", components: one("hvac.duct.modify", "duct modification") },
  { phrase: "bath fan", matchKind: "contains", priority: 90, components: one("hvac.bathfan.install", "bath exhaust fan") },
  { phrase: "exhaust fan", matchKind: "contains", priority: 88, components: one("hvac.bathfan.install", "exhaust fan") },
  { phrase: "range hood vent", matchKind: "contains", components: one("hvac.rangehood.vent", "range hood venting") },
  { phrase: "dryer vent", matchKind: "contains", components: one("hvac.dryer.vent", "dryer vent") },
  { phrase: "mini split", matchKind: "contains", components: one("hvac.minisplit.single", "mini-split system") },
  { phrase: "mini-split", matchKind: "contains", components: one("hvac.minisplit.single", "mini-split system") },
  { phrase: "thermostat", matchKind: "contains", priority: 80, components: one("hvac.thermostat.install", "thermostat") },

  /* ---------------- insulation ---------------- */
  { phrase: "rigid foam", matchKind: "contains", components: one("insulation.rigid.foam", "rigid foam") },
  { phrase: "spray foam", matchKind: "contains", components: one("insulation.spray.allowance", "spray foam allowance") },
  { phrase: "rim joist", matchKind: "contains", components: one("insulation.rimjoist.seal", "rim joist insulation") },
  { phrase: "air sealing", matchKind: "contains", components: one("insulation.airseal.package", "air sealing") },
  { phrase: "sound insulation", matchKind: "contains", components: one("insulation.sound.batt", "sound batt") },
  { phrase: "vapor barrier", matchKind: "contains", components: one("insulation.vapor.barrier", "vapor retarder") },
  { phrase: "attic insulation", matchKind: "contains", components: one("insulation.attic.blown", "blown insulation") },

  /* ---------------- doors and windows ---------------- */
  { phrase: "install prehung door", matchKind: "contains", priority: 95, components: one("doors.interior.prehung.install", "prehung door") },
  { phrase: "install interior door", matchKind: "contains", priority: 94, components: one("doors.interior.prehung.install", "interior door") },
  { phrase: "hang slab door", matchKind: "contains", components: one("doors.interior.slab", "slab door") },
  { phrase: "bifold door", matchKind: "contains", components: one("doors.bifold.install", "bifold door") },
  { phrase: "pocket door", matchKind: "contains", components: one("doors.pocket.install", "pocket door") },
  { phrase: "barn door", matchKind: "contains", components: one("doors.barn.install", "barn door") },
  { phrase: "install lockset", matchKind: "contains", components: one("doors.hardware.install", "door hardware") },
  { phrase: "door hardware", matchKind: "contains", priority: 85, components: one("doors.hardware.install", "door hardware") },
  { phrase: "adjust door", matchKind: "contains", components: one("doors.adjust.repair", "door adjustment") },
  { phrase: "install entry door", matchKind: "contains", priority: 95, components: one("doors.entry.install", "entry door") },
  { phrase: "exterior door", matchKind: "contains", priority: 86, components: one("doors.entry.install", "entry door") },
  { phrase: "patio door", matchKind: "contains", components: one("doors.patio.slider", "patio door") },
  { phrase: "storm door", matchKind: "contains", components: one("doors.storm.install", "storm door") },
  { phrase: "replace window", matchKind: "contains", priority: 92, components: one("windows.replace.insert", "window replacement") },
  { phrase: "install window", matchKind: "contains", priority: 90, components: one("windows.newconstruction.install", "window install") },
  { phrase: "egress window", matchKind: "contains", priority: 96, components: one("windows.egress.install", "egress window") },
  { phrase: "window sill", matchKind: "contains", components: one("windows.sill.interior", "sill and apron") },

  /* ---------------- finish carpentry ---------------- */
  { phrase: "install baseboard trim", matchKind: "contains", priority: 95, components: one("trim.base.install.paintgrade", "baseboard") },
  { phrase: "install baseboard", matchKind: "contains", priority: 94, components: one("trim.base.install.paintgrade", "baseboard") },
  { phrase: "install base trim", matchKind: "contains", priority: 93, components: one("trim.base.install.paintgrade", "baseboard") },
  { phrase: "install shoe molding", matchKind: "contains", components: one("trim.shoe.quarter", "shoe molding") },
  { phrase: "quarter round", matchKind: "contains", components: one("trim.shoe.quarter", "quarter round") },
  { phrase: "case doors", matchKind: "contains", components: one("trim.casing.door", "door casing") },
  { phrase: "install casing", matchKind: "contains", priority: 90, components: one("trim.casing.door", "casing") },
  { phrase: "install crown molding", matchKind: "contains", priority: 95, components: one("trim.crown.install", "crown molding") },
  { phrase: "wainscot", matchKind: "contains", components: one("trim.wainscot.panel", "wainscot") },
  { phrase: "board and batten", matchKind: "contains", components: one("trim.wainscot.panel", "panelling") },
  { phrase: "closet shelving", matchKind: "contains", components: one("trim.shelving.closet", "closet shelf and rod") },
  { phrase: "closet system", matchKind: "contains", components: one("trim.closet.system", "closet organizer") },
  { phrase: "install handrail", matchKind: "contains", components: one("trim.handrail.install", "handrail") },
  { phrase: "trim repair", matchKind: "contains", components: one("trim.repair.patch", "trim repair") },

  /* ---------------- cabinets and countertops ---------------- */
  { phrase: "install kitchen cabinets", matchKind: "contains", priority: 97, components: [
    { assemblyKey: "cabinets.base.install", quantityFactor: 1, role: "base cabinets" },
    { assemblyKey: "cabinets.wall.install", quantityFactor: 1, role: "wall cabinets" },
  ] },
  { phrase: "install base cabinets", matchKind: "contains", priority: 95, components: one("cabinets.base.install", "base cabinets") },
  { phrase: "install wall cabinets", matchKind: "contains", priority: 95, components: one("cabinets.wall.install", "wall cabinets") },
  { phrase: "install cabinets", matchKind: "contains", priority: 92, components: [
    { assemblyKey: "cabinets.base.install", quantityFactor: 1, role: "base cabinets" },
    { assemblyKey: "cabinets.wall.install", quantityFactor: 1, role: "wall cabinets" },
  ] },
  { phrase: "pantry cabinet", matchKind: "contains", components: one("cabinets.tall.install", "tall cabinet") },
  { phrase: "install vanity", matchKind: "contains", priority: 95, components: one("cabinets.vanity.install", "vanity") },
  { phrase: "cabinet hardware", matchKind: "contains", components: one("cabinets.hardware.install", "cabinet hardware") },
  { phrase: "cabinet crown", matchKind: "contains", components: one("cabinets.crown.install", "cabinet crown") },
  { phrase: "quartz countertop", matchKind: "contains", priority: 95, components: one("countertops.quartz.install", "quartz top") },
  { phrase: "granite countertop", matchKind: "contains", priority: 95, components: one("countertops.granite.install", "granite top") },
  { phrase: "laminate countertop", matchKind: "contains", priority: 95, components: one("countertops.laminate.install", "laminate top") },
  { phrase: "butcher block", matchKind: "contains", components: one("countertops.butcherblock.install", "butcher block top") },
  { phrase: "solid surface countertop", matchKind: "contains", components: one("countertops.solidsurface.install", "solid-surface top") },
  { phrase: "install countertops", matchKind: "contains", priority: 80, review: "ambiguous_material_selection",
    note: "Pick the countertop material (quartz, granite, laminate, solid surface or butcher block)." },

  /* ---------------- roofing / exterior ---------------- */
  { phrase: "install shingles", matchKind: "contains", priority: 95, components: one("roofing.asphalt.install", "asphalt shingles") },
  { phrase: "asphalt shingle roof", matchKind: "contains", components: one("roofing.asphalt.install", "asphalt shingles") },
  { phrase: "roof underlayment", matchKind: "contains", components: one("roofing.underlayment.install", "underlayment") },
  { phrase: "ice and water", matchKind: "contains", components: one("roofing.iceandwater.install", "ice barrier") },
  { phrase: "ridge vent", matchKind: "contains", components: one("roofing.ridge.vent", "ridge vent") },
  { phrase: "step flashing", matchKind: "contains", components: one("roofing.flashing.step", "flashing") },
  { phrase: "pipe boot", matchKind: "contains", components: one("roofing.pipe.boot", "penetration flashing") },
  { phrase: "sheathing repair", matchKind: "contains", components: one("roofing.sheathing.repair", "decking repair allowance") },
  { phrase: "install vinyl siding", matchKind: "contains", priority: 95, components: one("siding.vinyl.install", "vinyl siding") },
  { phrase: "fiber cement siding", matchKind: "contains", priority: 95, components: one("siding.fibercement.install", "fiber-cement siding") },
  { phrase: "house wrap", matchKind: "contains", components: one("siding.wrap.install", "weather barrier") },
  { phrase: "soffit and fascia", matchKind: "contains", components: one("siding.soffit.fascia", "soffit and fascia") },
  { phrase: "siding repair", matchKind: "contains", components: one("siding.repair.patch", "siding repair") },
  { phrase: "install gutters", matchKind: "contains", priority: 95, components: [
    { assemblyKey: "gutters.k5.install", quantityFactor: 1, role: "gutter" },
    { assemblyKey: "gutters.downspout.install", quantityFactor: 0.25, role: "downspouts" },
  ] },
  { phrase: "gutter guards", matchKind: "contains", components: one("gutters.guard.install", "gutter guards") },
  { phrase: "downspout extension", matchKind: "contains", components: one("gutters.extension.drain", "downspout extension") },

  /* ---------------- concrete / masonry ---------------- */
  { phrase: "pour concrete slab", matchKind: "contains", priority: 95, components: one("concrete.slab.pour", "slab") },
  { phrase: "concrete walkway", matchKind: "contains", components: one("concrete.walkway.pour", "walkway") },
  { phrase: "equipment pad", matchKind: "contains", components: one("concrete.pad.equipment", "equipment pad") },
  { phrase: "pour footing", matchKind: "contains", components: one("concrete.footing.pour", "footing") },
  { phrase: "concrete steps", matchKind: "contains", components: one("concrete.steps.pour", "steps") },
  { phrase: "concrete repair", matchKind: "contains", components: one("concrete.patch.repair", "concrete repair") },
  { phrase: "saw cut concrete", matchKind: "contains", components: one("concrete.saw.cut", "saw cutting") },
  { phrase: "block wall", matchKind: "contains", components: one("masonry.block.wall", "CMU wall") },
  { phrase: "frost wall", matchKind: "contains", components: one("masonry.frostwall.pour", "frost wall") },
  { phrase: "tuckpoint", matchKind: "contains", components: one("masonry.tuckpoint.repair", "repointing") },
  { phrase: "brick repair", matchKind: "contains", components: one("masonry.brick.repair", "brick repair") },
  { phrase: "stone veneer", matchKind: "contains", components: one("masonry.veneer.stone", "stone veneer") },
  { phrase: "chimney repair", matchKind: "contains", components: one("masonry.chimney.repair", "chimney repair") },

  /* ---------------- decks ---------------- */
  { phrase: "deck footing", matchKind: "contains", components: one("decks.footing.install", "footings") },
  { phrase: "frame deck", matchKind: "contains", priority: 95, components: one("decks.framing.install", "deck framing") },
  { phrase: "composite decking", matchKind: "contains", priority: 95, components: one("decks.decking.composite", "composite decking") },
  { phrase: "install decking", matchKind: "contains", priority: 90, components: one("decks.decking.wood", "decking") },
  { phrase: "deck stairs", matchKind: "contains", components: one("decks.stairs.build", "deck stairs") },
  { phrase: "deck railing", matchKind: "contains", priority: 95, components: one("decks.railing.install", "deck railing") },
  { phrase: "deck skirting", matchKind: "contains", components: one("decks.skirting.install", "skirting") },
  { phrase: "deck repair", matchKind: "contains", components: one("decks.repair.boards", "deck repair") },

  /* ---------------- handyman ---------------- */
  { phrase: "recaulk", matchKind: "contains", components: one("handyman.caulk.refresh", "caulk joint") },
  { phrase: "replace caulk", matchKind: "contains", components: one("handyman.caulk.refresh", "caulk joint") },
  { phrase: "install shelf", matchKind: "contains", components: one("handyman.shelf.install", "wall shelf") },
  { phrase: "mount tv", matchKind: "contains", components: one("handyman.tv.mount", "TV mount") },
  { phrase: "grab bar", matchKind: "contains", components: one("handyman.grabbar.install", "grab bar") },
  { phrase: "toilet repair", matchKind: "contains", components: one("handyman.toilet.repair", "toilet repair") },
  { phrase: "medicine cabinet", matchKind: "contains", components: one("handyman.mirror.install", "mirror/cabinet") },
  { phrase: "towel bar", matchKind: "contains", components: one("handyman.towelbar.accessory", "bath accessory") },
  { phrase: "screen repair", matchKind: "contains", components: one("handyman.screen.repair", "screen repair") },
  { phrase: "punch list", matchKind: "contains", components: one("handyman.punch.hour", "punch-list labor") },
  { phrase: "weatherstripping", matchKind: "contains", components: one("handyman.weatherstrip.door", "weatherstripping") },

  /* ---------------- site / landscaping ---------------- */
  { phrase: "rough grading", matchKind: "contains", priority: 95, components: one("site.grading.rough", "grading") },
  { phrase: "grade around foundation", matchKind: "contains", components: one("site.grading.rough", "grading") },
  { phrase: "excavate trench", matchKind: "contains", components: one("site.excavation.trench", "trenching") },
  { phrase: "french drain", matchKind: "contains", components: one("site.drainage.french", "french drain") },
  { phrase: "topsoil and seed", matchKind: "contains", components: one("site.topsoil.seed", "topsoil and seed") },
  { phrase: "install sod", matchKind: "contains", components: one("site.sod.install", "sod") },
  { phrase: "mulch beds", matchKind: "contains", components: one("site.mulch.beds", "mulch") },
  { phrase: "retaining wall", matchKind: "contains", components: one("site.retaining.small", "retaining wall") },
  { phrase: "privacy fence", matchKind: "contains", priority: 95, components: one("site.fence.privacy", "fence") },
  { phrase: "install fence", matchKind: "contains", priority: 90, components: one("site.fence.privacy", "fence") },
];
