import { admitScope } from "@/domains/scopeAdmission";
import { WORK_RULES, localized } from "@/domains/remoteVision/lexicon";
import { stripSpatialContext } from "@/domains/remoteVision/spatialContext";
const TEXT = "Okay, so this project is actually three little handyman projects. The first is the exterior. Remove and replace approximately 56 linear feet of 1x6 fascia, which includes a 1x2 shadow board. All of these three little handyman projects will be labor-only quotes. The fascia will be painted also. The second little handyman project is we're going to put a 2-inch thick rigid foam insulation on the ceiling in the basement there. That basement measures approximately 10 feet by 21 feet. We're going to seal all the seams with tape and then spray foam the perimeter gaps. We're going to screw the rigid foam up to the ceiling with screws and washers. The third little handyman project is that bathroom hole in the wall. That's a plumbing chase. We're going to build an access door, which measures approximately 19 inches by 42 inches tall. We're going to build it out of 1x4 lumber with a quarter-inch thick plywood back, and we're going to put some hinges on it and paint it white to match the trim.";
const lines = TEXT.split(/(?<=[.!?;\n])\s+/).map(s=>s.trim()).filter(Boolean);
const matched = WORK_RULES.map(rule=>({rule, hit: lines.find(l=>rule.match.test(stripSpatialContext(l)))})).filter(h=>h.hit) as any[];
console.log("MATCHED", matched.map(m=>m.rule.featureKey));
const superseded = new Set(matched.flatMap(h=>h.rule.supersedes ?? []));
const keywordHits = matched.filter(h=>!superseded.has(h.rule.featureKey));
const admission = admitScope({ text: TEXT, candidates: keywordHits.map(({rule,hit})=>({featureKey:rule.featureKey,label:localized(rule.label,"en-US"),sentence:hit.trim(),source:"description" as const})) });
console.log("ADMITTED", admission.admitted.map(a=>[a.featureKey,a.action,a.singularCount]));
console.log("SUGGESTED", admission.suggested.map(s=>[s.featureKey,s.code]));
